// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ai/ent/aiapikey"
	"ai/ent/aimodel"
	"ai/ent/predicate"
	"context"
	"entmodule"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AiApiKeyUpdate is the builder for updating AiApiKey entities.
type AiApiKeyUpdate struct {
	config
	hooks    []Hook
	mutation *AiApiKeyMutation
}

// Where appends a list predicates to the AiApiKeyUpdate builder.
func (_u *AiApiKeyUpdate) Where(ps ...predicate.AiApiKey) *AiApiKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AiApiKeyUpdate) SetUpdatedAt(v time.Time) *AiApiKeyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AiApiKeyUpdate) SetDeletedAt(v time.Time) *AiApiKeyUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AiApiKeyUpdate) SetNillableDeletedAt(v *time.Time) *AiApiKeyUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AiApiKeyUpdate) ClearDeletedAt() *AiApiKeyUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *AiApiKeyUpdate) SetName(v string) *AiApiKeyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AiApiKeyUpdate) SetNillableName(v *string) *AiApiKeyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *AiApiKeyUpdate) SetAPIKey(v string) *AiApiKeyUpdate {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *AiApiKeyUpdate) SetNillableAPIKey(v *string) *AiApiKeyUpdate {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *AiApiKeyUpdate) SetPlatform(v string) *AiApiKeyUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *AiApiKeyUpdate) SetNillablePlatform(v *string) *AiApiKeyUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *AiApiKeyUpdate) SetURL(v string) *AiApiKeyUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *AiApiKeyUpdate) SetNillableURL(v *string) *AiApiKeyUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AiApiKeyUpdate) SetStatus(v entmodule.Status) *AiApiKeyUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AiApiKeyUpdate) SetNillableStatus(v *entmodule.Status) *AiApiKeyUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddAiModelIDs adds the "ai_model" edge to the AiModel entity by IDs.
func (_u *AiApiKeyUpdate) AddAiModelIDs(ids ...int) *AiApiKeyUpdate {
	_u.mutation.AddAiModelIDs(ids...)
	return _u
}

// AddAiModel adds the "ai_model" edges to the AiModel entity.
func (_u *AiApiKeyUpdate) AddAiModel(v ...*AiModel) *AiApiKeyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAiModelIDs(ids...)
}

// Mutation returns the AiApiKeyMutation object of the builder.
func (_u *AiApiKeyUpdate) Mutation() *AiApiKeyMutation {
	return _u.mutation
}

// ClearAiModel clears all "ai_model" edges to the AiModel entity.
func (_u *AiApiKeyUpdate) ClearAiModel() *AiApiKeyUpdate {
	_u.mutation.ClearAiModel()
	return _u
}

// RemoveAiModelIDs removes the "ai_model" edge to AiModel entities by IDs.
func (_u *AiApiKeyUpdate) RemoveAiModelIDs(ids ...int) *AiApiKeyUpdate {
	_u.mutation.RemoveAiModelIDs(ids...)
	return _u
}

// RemoveAiModel removes "ai_model" edges to AiModel entities.
func (_u *AiApiKeyUpdate) RemoveAiModel(v ...*AiModel) *AiApiKeyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAiModelIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AiApiKeyUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AiApiKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AiApiKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AiApiKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AiApiKeyUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if aiapikey.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized aiapikey.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := aiapikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AiApiKeyUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := aiapikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AiApiKey.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKey(); ok {
		if err := aiapikey.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "AiApiKey.api_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := aiapikey.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "AiApiKey.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := aiapikey.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "AiApiKey.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := aiapikey.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AiApiKey.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AiApiKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aiapikey.Table, aiapikey.Columns, sqlgraph.NewFieldSpec(aiapikey.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aiapikey.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(aiapikey.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(aiapikey.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(aiapikey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(aiapikey.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(aiapikey.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(aiapikey.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(aiapikey.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.AiModelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aiapikey.AiModelTable,
			Columns: []string{aiapikey.AiModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aimodel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAiModelIDs(); len(nodes) > 0 && !_u.mutation.AiModelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aiapikey.AiModelTable,
			Columns: []string{aiapikey.AiModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aimodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AiModelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aiapikey.AiModelTable,
			Columns: []string{aiapikey.AiModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aimodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aiapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AiApiKeyUpdateOne is the builder for updating a single AiApiKey entity.
type AiApiKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AiApiKeyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AiApiKeyUpdateOne) SetUpdatedAt(v time.Time) *AiApiKeyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AiApiKeyUpdateOne) SetDeletedAt(v time.Time) *AiApiKeyUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AiApiKeyUpdateOne) SetNillableDeletedAt(v *time.Time) *AiApiKeyUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AiApiKeyUpdateOne) ClearDeletedAt() *AiApiKeyUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *AiApiKeyUpdateOne) SetName(v string) *AiApiKeyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AiApiKeyUpdateOne) SetNillableName(v *string) *AiApiKeyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *AiApiKeyUpdateOne) SetAPIKey(v string) *AiApiKeyUpdateOne {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *AiApiKeyUpdateOne) SetNillableAPIKey(v *string) *AiApiKeyUpdateOne {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *AiApiKeyUpdateOne) SetPlatform(v string) *AiApiKeyUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *AiApiKeyUpdateOne) SetNillablePlatform(v *string) *AiApiKeyUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *AiApiKeyUpdateOne) SetURL(v string) *AiApiKeyUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *AiApiKeyUpdateOne) SetNillableURL(v *string) *AiApiKeyUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AiApiKeyUpdateOne) SetStatus(v entmodule.Status) *AiApiKeyUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AiApiKeyUpdateOne) SetNillableStatus(v *entmodule.Status) *AiApiKeyUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddAiModelIDs adds the "ai_model" edge to the AiModel entity by IDs.
func (_u *AiApiKeyUpdateOne) AddAiModelIDs(ids ...int) *AiApiKeyUpdateOne {
	_u.mutation.AddAiModelIDs(ids...)
	return _u
}

// AddAiModel adds the "ai_model" edges to the AiModel entity.
func (_u *AiApiKeyUpdateOne) AddAiModel(v ...*AiModel) *AiApiKeyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAiModelIDs(ids...)
}

// Mutation returns the AiApiKeyMutation object of the builder.
func (_u *AiApiKeyUpdateOne) Mutation() *AiApiKeyMutation {
	return _u.mutation
}

// ClearAiModel clears all "ai_model" edges to the AiModel entity.
func (_u *AiApiKeyUpdateOne) ClearAiModel() *AiApiKeyUpdateOne {
	_u.mutation.ClearAiModel()
	return _u
}

// RemoveAiModelIDs removes the "ai_model" edge to AiModel entities by IDs.
func (_u *AiApiKeyUpdateOne) RemoveAiModelIDs(ids ...int) *AiApiKeyUpdateOne {
	_u.mutation.RemoveAiModelIDs(ids...)
	return _u
}

// RemoveAiModel removes "ai_model" edges to AiModel entities.
func (_u *AiApiKeyUpdateOne) RemoveAiModel(v ...*AiModel) *AiApiKeyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAiModelIDs(ids...)
}

// Where appends a list predicates to the AiApiKeyUpdate builder.
func (_u *AiApiKeyUpdateOne) Where(ps ...predicate.AiApiKey) *AiApiKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AiApiKeyUpdateOne) Select(field string, fields ...string) *AiApiKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AiApiKey entity.
func (_u *AiApiKeyUpdateOne) Save(ctx context.Context) (*AiApiKey, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AiApiKeyUpdateOne) SaveX(ctx context.Context) *AiApiKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AiApiKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AiApiKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AiApiKeyUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if aiapikey.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized aiapikey.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := aiapikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AiApiKeyUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := aiapikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AiApiKey.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKey(); ok {
		if err := aiapikey.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "AiApiKey.api_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := aiapikey.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "AiApiKey.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := aiapikey.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "AiApiKey.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := aiapikey.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AiApiKey.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AiApiKeyUpdateOne) sqlSave(ctx context.Context) (_node *AiApiKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aiapikey.Table, aiapikey.Columns, sqlgraph.NewFieldSpec(aiapikey.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AiApiKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aiapikey.FieldID)
		for _, f := range fields {
			if !aiapikey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aiapikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aiapikey.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(aiapikey.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(aiapikey.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(aiapikey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(aiapikey.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(aiapikey.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(aiapikey.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(aiapikey.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.AiModelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aiapikey.AiModelTable,
			Columns: []string{aiapikey.AiModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aimodel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAiModelIDs(); len(nodes) > 0 && !_u.mutation.AiModelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aiapikey.AiModelTable,
			Columns: []string{aiapikey.AiModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aimodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AiModelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aiapikey.AiModelTable,
			Columns: []string{aiapikey.AiModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aimodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AiApiKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aiapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
