// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ai/ent/aiapikey"
	"ai/ent/aimodel"
	"context"
	"entmodule"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AiApiKeyCreate is the builder for creating a AiApiKey entity.
type AiApiKeyCreate struct {
	config
	mutation *AiApiKeyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AiApiKeyCreate) SetCreatedAt(v time.Time) *AiApiKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AiApiKeyCreate) SetNillableCreatedAt(v *time.Time) *AiApiKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AiApiKeyCreate) SetUpdatedAt(v time.Time) *AiApiKeyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AiApiKeyCreate) SetNillableUpdatedAt(v *time.Time) *AiApiKeyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AiApiKeyCreate) SetDeletedAt(v time.Time) *AiApiKeyCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *AiApiKeyCreate) SetNillableDeletedAt(v *time.Time) *AiApiKeyCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AiApiKeyCreate) SetName(v string) *AiApiKeyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAPIKey sets the "api_key" field.
func (_c *AiApiKeyCreate) SetAPIKey(v string) *AiApiKeyCreate {
	_c.mutation.SetAPIKey(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *AiApiKeyCreate) SetPlatform(v string) *AiApiKeyCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *AiApiKeyCreate) SetURL(v string) *AiApiKeyCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *AiApiKeyCreate) SetNillableURL(v *string) *AiApiKeyCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AiApiKeyCreate) SetStatus(v entmodule.Status) *AiApiKeyCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// AddAiModelIDs adds the "ai_model" edge to the AiModel entity by IDs.
func (_c *AiApiKeyCreate) AddAiModelIDs(ids ...int) *AiApiKeyCreate {
	_c.mutation.AddAiModelIDs(ids...)
	return _c
}

// AddAiModel adds the "ai_model" edges to the AiModel entity.
func (_c *AiApiKeyCreate) AddAiModel(v ...*AiModel) *AiApiKeyCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAiModelIDs(ids...)
}

// Mutation returns the AiApiKeyMutation object of the builder.
func (_c *AiApiKeyCreate) Mutation() *AiApiKeyMutation {
	return _c.mutation
}

// Save creates the AiApiKey in the database.
func (_c *AiApiKeyCreate) Save(ctx context.Context) (*AiApiKey, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AiApiKeyCreate) SaveX(ctx context.Context) *AiApiKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AiApiKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AiApiKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AiApiKeyCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if aiapikey.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized aiapikey.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := aiapikey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if aiapikey.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized aiapikey.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := aiapikey.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.URL(); !ok {
		v := aiapikey.DefaultURL
		_c.mutation.SetURL(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *AiApiKeyCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AiApiKey.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AiApiKey.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AiApiKey.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := aiapikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AiApiKey.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIKey(); !ok {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required field "AiApiKey.api_key"`)}
	}
	if v, ok := _c.mutation.APIKey(); ok {
		if err := aiapikey.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "AiApiKey.api_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "AiApiKey.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := aiapikey.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "AiApiKey.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "AiApiKey.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := aiapikey.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "AiApiKey.url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AiApiKey.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := aiapikey.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AiApiKey.status": %w`, err)}
		}
	}
	return nil
}

func (_c *AiApiKeyCreate) sqlSave(ctx context.Context) (*AiApiKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AiApiKeyCreate) createSpec() (*AiApiKey, *sqlgraph.CreateSpec) {
	var (
		_node = &AiApiKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(aiapikey.Table, sqlgraph.NewFieldSpec(aiapikey.FieldID, field.TypeInt))
	)

	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(aiapikey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(aiapikey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(aiapikey.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(aiapikey.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.APIKey(); ok {
		_spec.SetField(aiapikey.FieldAPIKey, field.TypeString, value)
		_node.APIKey = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(aiapikey.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(aiapikey.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(aiapikey.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.AiModelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aiapikey.AiModelTable,
			Columns: []string{aiapikey.AiModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aimodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AiApiKey.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AiApiKeyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AiApiKeyCreate) OnConflict(opts ...sql.ConflictOption) *AiApiKeyUpsertOne {
	_c.conflict = opts
	return &AiApiKeyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AiApiKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AiApiKeyCreate) OnConflictColumns(columns ...string) *AiApiKeyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AiApiKeyUpsertOne{
		create: _c,
	}
}

type (
	// AiApiKeyUpsertOne is the builder for "upsert"-ing
	//  one AiApiKey node.
	AiApiKeyUpsertOne struct {
		create *AiApiKeyCreate
	}

	// AiApiKeyUpsert is the "OnConflict" setter.
	AiApiKeyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AiApiKeyUpsert) SetUpdatedAt(v time.Time) *AiApiKeyUpsert {
	u.Set(aiapikey.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AiApiKeyUpsert) UpdateUpdatedAt() *AiApiKeyUpsert {
	u.SetExcluded(aiapikey.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AiApiKeyUpsert) SetDeletedAt(v time.Time) *AiApiKeyUpsert {
	u.Set(aiapikey.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AiApiKeyUpsert) UpdateDeletedAt() *AiApiKeyUpsert {
	u.SetExcluded(aiapikey.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AiApiKeyUpsert) ClearDeletedAt() *AiApiKeyUpsert {
	u.SetNull(aiapikey.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *AiApiKeyUpsert) SetName(v string) *AiApiKeyUpsert {
	u.Set(aiapikey.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AiApiKeyUpsert) UpdateName() *AiApiKeyUpsert {
	u.SetExcluded(aiapikey.FieldName)
	return u
}

// SetAPIKey sets the "api_key" field.
func (u *AiApiKeyUpsert) SetAPIKey(v string) *AiApiKeyUpsert {
	u.Set(aiapikey.FieldAPIKey, v)
	return u
}

// UpdateAPIKey sets the "api_key" field to the value that was provided on create.
func (u *AiApiKeyUpsert) UpdateAPIKey() *AiApiKeyUpsert {
	u.SetExcluded(aiapikey.FieldAPIKey)
	return u
}

// SetPlatform sets the "platform" field.
func (u *AiApiKeyUpsert) SetPlatform(v string) *AiApiKeyUpsert {
	u.Set(aiapikey.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *AiApiKeyUpsert) UpdatePlatform() *AiApiKeyUpsert {
	u.SetExcluded(aiapikey.FieldPlatform)
	return u
}

// SetURL sets the "url" field.
func (u *AiApiKeyUpsert) SetURL(v string) *AiApiKeyUpsert {
	u.Set(aiapikey.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *AiApiKeyUpsert) UpdateURL() *AiApiKeyUpsert {
	u.SetExcluded(aiapikey.FieldURL)
	return u
}

// SetStatus sets the "status" field.
func (u *AiApiKeyUpsert) SetStatus(v entmodule.Status) *AiApiKeyUpsert {
	u.Set(aiapikey.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AiApiKeyUpsert) UpdateStatus() *AiApiKeyUpsert {
	u.SetExcluded(aiapikey.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AiApiKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AiApiKeyUpsertOne) UpdateNewValues() *AiApiKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(aiapikey.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AiApiKey.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AiApiKeyUpsertOne) Ignore() *AiApiKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AiApiKeyUpsertOne) DoNothing() *AiApiKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AiApiKeyCreate.OnConflict
// documentation for more info.
func (u *AiApiKeyUpsertOne) Update(set func(*AiApiKeyUpsert)) *AiApiKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AiApiKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AiApiKeyUpsertOne) SetUpdatedAt(v time.Time) *AiApiKeyUpsertOne {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AiApiKeyUpsertOne) UpdateUpdatedAt() *AiApiKeyUpsertOne {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AiApiKeyUpsertOne) SetDeletedAt(v time.Time) *AiApiKeyUpsertOne {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AiApiKeyUpsertOne) UpdateDeletedAt() *AiApiKeyUpsertOne {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AiApiKeyUpsertOne) ClearDeletedAt() *AiApiKeyUpsertOne {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *AiApiKeyUpsertOne) SetName(v string) *AiApiKeyUpsertOne {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AiApiKeyUpsertOne) UpdateName() *AiApiKeyUpsertOne {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.UpdateName()
	})
}

// SetAPIKey sets the "api_key" field.
func (u *AiApiKeyUpsertOne) SetAPIKey(v string) *AiApiKeyUpsertOne {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.SetAPIKey(v)
	})
}

// UpdateAPIKey sets the "api_key" field to the value that was provided on create.
func (u *AiApiKeyUpsertOne) UpdateAPIKey() *AiApiKeyUpsertOne {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.UpdateAPIKey()
	})
}

// SetPlatform sets the "platform" field.
func (u *AiApiKeyUpsertOne) SetPlatform(v string) *AiApiKeyUpsertOne {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *AiApiKeyUpsertOne) UpdatePlatform() *AiApiKeyUpsertOne {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.UpdatePlatform()
	})
}

// SetURL sets the "url" field.
func (u *AiApiKeyUpsertOne) SetURL(v string) *AiApiKeyUpsertOne {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *AiApiKeyUpsertOne) UpdateURL() *AiApiKeyUpsertOne {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.UpdateURL()
	})
}

// SetStatus sets the "status" field.
func (u *AiApiKeyUpsertOne) SetStatus(v entmodule.Status) *AiApiKeyUpsertOne {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AiApiKeyUpsertOne) UpdateStatus() *AiApiKeyUpsertOne {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *AiApiKeyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AiApiKeyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AiApiKeyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AiApiKeyUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AiApiKeyUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *AiApiKeyCreate) SetRawID(t int) *AiApiKeyCreate {
	m.mutation.SetRawID(t)
	return m
}

// AiApiKeyCreateBulk is the builder for creating many AiApiKey entities in bulk.
type AiApiKeyCreateBulk struct {
	config
	err      error
	builders []*AiApiKeyCreate
	conflict []sql.ConflictOption
}

// Save creates the AiApiKey entities in the database.
func (_c *AiApiKeyCreateBulk) Save(ctx context.Context) ([]*AiApiKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AiApiKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AiApiKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AiApiKeyCreateBulk) SaveX(ctx context.Context) []*AiApiKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AiApiKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AiApiKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AiApiKey.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AiApiKeyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AiApiKeyCreateBulk) OnConflict(opts ...sql.ConflictOption) *AiApiKeyUpsertBulk {
	_c.conflict = opts
	return &AiApiKeyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AiApiKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AiApiKeyCreateBulk) OnConflictColumns(columns ...string) *AiApiKeyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AiApiKeyUpsertBulk{
		create: _c,
	}
}

// AiApiKeyUpsertBulk is the builder for "upsert"-ing
// a bulk of AiApiKey nodes.
type AiApiKeyUpsertBulk struct {
	create *AiApiKeyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AiApiKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AiApiKeyUpsertBulk) UpdateNewValues() *AiApiKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(aiapikey.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AiApiKey.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AiApiKeyUpsertBulk) Ignore() *AiApiKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AiApiKeyUpsertBulk) DoNothing() *AiApiKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AiApiKeyCreateBulk.OnConflict
// documentation for more info.
func (u *AiApiKeyUpsertBulk) Update(set func(*AiApiKeyUpsert)) *AiApiKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AiApiKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AiApiKeyUpsertBulk) SetUpdatedAt(v time.Time) *AiApiKeyUpsertBulk {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AiApiKeyUpsertBulk) UpdateUpdatedAt() *AiApiKeyUpsertBulk {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AiApiKeyUpsertBulk) SetDeletedAt(v time.Time) *AiApiKeyUpsertBulk {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AiApiKeyUpsertBulk) UpdateDeletedAt() *AiApiKeyUpsertBulk {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AiApiKeyUpsertBulk) ClearDeletedAt() *AiApiKeyUpsertBulk {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *AiApiKeyUpsertBulk) SetName(v string) *AiApiKeyUpsertBulk {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AiApiKeyUpsertBulk) UpdateName() *AiApiKeyUpsertBulk {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.UpdateName()
	})
}

// SetAPIKey sets the "api_key" field.
func (u *AiApiKeyUpsertBulk) SetAPIKey(v string) *AiApiKeyUpsertBulk {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.SetAPIKey(v)
	})
}

// UpdateAPIKey sets the "api_key" field to the value that was provided on create.
func (u *AiApiKeyUpsertBulk) UpdateAPIKey() *AiApiKeyUpsertBulk {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.UpdateAPIKey()
	})
}

// SetPlatform sets the "platform" field.
func (u *AiApiKeyUpsertBulk) SetPlatform(v string) *AiApiKeyUpsertBulk {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *AiApiKeyUpsertBulk) UpdatePlatform() *AiApiKeyUpsertBulk {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.UpdatePlatform()
	})
}

// SetURL sets the "url" field.
func (u *AiApiKeyUpsertBulk) SetURL(v string) *AiApiKeyUpsertBulk {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *AiApiKeyUpsertBulk) UpdateURL() *AiApiKeyUpsertBulk {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.UpdateURL()
	})
}

// SetStatus sets the "status" field.
func (u *AiApiKeyUpsertBulk) SetStatus(v entmodule.Status) *AiApiKeyUpsertBulk {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AiApiKeyUpsertBulk) UpdateStatus() *AiApiKeyUpsertBulk {
	return u.Update(func(s *AiApiKeyUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *AiApiKeyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AiApiKeyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AiApiKeyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AiApiKeyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
