// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ai/ent/aiapikey"
	"ai/ent/aimodel"
	"ai/ent/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AiApiKeyQuery is the builder for querying AiApiKey entities.
type AiApiKeyQuery struct {
	config
	ctx         *QueryContext
	order       []aiapikey.OrderOption
	inters      []Interceptor
	predicates  []predicate.AiApiKey
	withAiModel *AiModelQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AiApiKeyQuery builder.
func (_q *AiApiKeyQuery) Where(ps ...predicate.AiApiKey) *AiApiKeyQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AiApiKeyQuery) Limit(limit int) *AiApiKeyQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AiApiKeyQuery) Offset(offset int) *AiApiKeyQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AiApiKeyQuery) Unique(unique bool) *AiApiKeyQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AiApiKeyQuery) Order(o ...aiapikey.OrderOption) *AiApiKeyQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAiModel chains the current query on the "ai_model" edge.
func (_q *AiApiKeyQuery) QueryAiModel() *AiModelQuery {
	query := (&AiModelClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(aiapikey.Table, aiapikey.FieldID, selector),
			sqlgraph.To(aimodel.Table, aimodel.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, aiapikey.AiModelTable, aiapikey.AiModelColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AiApiKey entity from the query.
// Returns a *NotFoundError when no AiApiKey was found.
func (_q *AiApiKeyQuery) First(ctx context.Context) (*AiApiKey, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{aiapikey.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AiApiKeyQuery) FirstX(ctx context.Context) *AiApiKey {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AiApiKey ID from the query.
// Returns a *NotFoundError when no AiApiKey ID was found.
func (_q *AiApiKeyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{aiapikey.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AiApiKeyQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AiApiKey entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AiApiKey entity is found.
// Returns a *NotFoundError when no AiApiKey entities are found.
func (_q *AiApiKeyQuery) Only(ctx context.Context) (*AiApiKey, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{aiapikey.Label}
	default:
		return nil, &NotSingularError{aiapikey.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AiApiKeyQuery) OnlyX(ctx context.Context) *AiApiKey {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AiApiKey ID in the query.
// Returns a *NotSingularError when more than one AiApiKey ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AiApiKeyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{aiapikey.Label}
	default:
		err = &NotSingularError{aiapikey.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AiApiKeyQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AiApiKeys.
func (_q *AiApiKeyQuery) All(ctx context.Context) ([]*AiApiKey, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AiApiKey, *AiApiKeyQuery]()
	return withInterceptors[[]*AiApiKey](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AiApiKeyQuery) AllX(ctx context.Context) []*AiApiKey {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AiApiKey IDs.
func (_q *AiApiKeyQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(aiapikey.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AiApiKeyQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AiApiKeyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AiApiKeyQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AiApiKeyQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AiApiKeyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AiApiKeyQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AiApiKeyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AiApiKeyQuery) Clone() *AiApiKeyQuery {
	if _q == nil {
		return nil
	}
	return &AiApiKeyQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]aiapikey.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.AiApiKey{}, _q.predicates...),
		withAiModel: _q.withAiModel.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithAiModel tells the query-builder to eager-load the nodes that are connected to
// the "ai_model" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AiApiKeyQuery) WithAiModel(opts ...func(*AiModelQuery)) *AiApiKeyQuery {
	query := (&AiModelClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAiModel = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AiApiKey.Query().
//		GroupBy(aiapikey.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AiApiKeyQuery) GroupBy(field string, fields ...string) *AiApiKeyGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AiApiKeyGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = aiapikey.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.AiApiKey.Query().
//		Select(aiapikey.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *AiApiKeyQuery) Select(fields ...string) *AiApiKeySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AiApiKeySelect{AiApiKeyQuery: _q}
	sbuild.label = aiapikey.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AiApiKeySelect configured with the given aggregations.
func (_q *AiApiKeyQuery) Aggregate(fns ...AggregateFunc) *AiApiKeySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AiApiKeyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !aiapikey.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AiApiKeyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AiApiKey, error) {
	var (
		nodes       = []*AiApiKey{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withAiModel != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AiApiKey).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AiApiKey{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAiModel; query != nil {
		if err := _q.loadAiModel(ctx, query, nodes,
			func(n *AiApiKey) { n.Edges.AiModel = []*AiModel{} },
			func(n *AiApiKey, e *AiModel) { n.Edges.AiModel = append(n.Edges.AiModel, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AiApiKeyQuery) loadAiModel(ctx context.Context, query *AiModelQuery, nodes []*AiApiKey, init func(*AiApiKey), assign func(*AiApiKey, *AiModel)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*AiApiKey)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(aimodel.FieldKeyID)
	}
	query.Where(predicate.AiModel(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(aiapikey.AiModelColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.KeyID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "key_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *AiApiKeyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AiApiKeyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(aiapikey.Table, aiapikey.Columns, sqlgraph.NewFieldSpec(aiapikey.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aiapikey.FieldID)
		for i := range fields {
			if fields[i] != aiapikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AiApiKeyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(aiapikey.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = aiapikey.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AiApiKeyGroupBy is the group-by builder for AiApiKey entities.
type AiApiKeyGroupBy struct {
	selector
	build *AiApiKeyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AiApiKeyGroupBy) Aggregate(fns ...AggregateFunc) *AiApiKeyGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AiApiKeyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AiApiKeyQuery, *AiApiKeyGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AiApiKeyGroupBy) sqlScan(ctx context.Context, root *AiApiKeyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AiApiKeySelect is the builder for selecting fields of AiApiKey entities.
type AiApiKeySelect struct {
	*AiApiKeyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AiApiKeySelect) Aggregate(fns ...AggregateFunc) *AiApiKeySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AiApiKeySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AiApiKeyQuery, *AiApiKeySelect](ctx, _s.AiApiKeyQuery, _s, _s.inters, v)
}

func (_s *AiApiKeySelect) sqlScan(ctx context.Context, root *AiApiKeyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
