// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ai/ent/aichatrole"
	"ai/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AiChatRoleDelete is the builder for deleting a AiChatRole entity.
type AiChatRoleDelete struct {
	config
	hooks    []Hook
	mutation *AiChatRoleMutation
}

// Where appends a list predicates to the AiChatRoleDelete builder.
func (_d *AiChatRoleDelete) Where(ps ...predicate.AiChatRole) *AiChatRoleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AiChatRoleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AiChatRoleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AiChatRoleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(aichatrole.Table, sqlgraph.NewFieldSpec(aichatrole.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AiChatRoleDeleteOne is the builder for deleting a single AiChatRole entity.
type AiChatRoleDeleteOne struct {
	_d *AiChatRoleDelete
}

// Where appends a list predicates to the AiChatRoleDelete builder.
func (_d *AiChatRoleDeleteOne) Where(ps ...predicate.AiChatRole) *AiChatRoleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AiChatRoleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{aichatrole.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AiChatRoleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
