// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ai/ent/aiimage"
	"ai/internal/biz/types"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AiImage is the model entity for the AiImage schema.
type AiImage struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 用户ID
	UserID int `json:"user_id,omitempty"`
	// 平台
	Platform string `json:"platform,omitempty"`
	// 模型ID
	ModelID int `json:"model_id,omitempty"`
	// 模型标识
	Model string `json:"model,omitempty"`
	// 提示
	Prompt string `json:"prompt,omitempty"`
	// 宽度
	Width int `json:"width,omitempty"`
	// 高度
	Height int `json:"height,omitempty"`
	// 绘制参数
	Options map[string]interface{} `json:"options,omitempty"`
	// 状态
	Status types.ImageStatus `json:"status,omitempty"`
	// 图片URL
	PicURL string `json:"pic_url,omitempty"`
	// 任务编号
	TaskID string `json:"task_id,omitempty"`
	// mj 按钮
	Buttons      string `json:"buttons,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AiImage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aiimage.FieldOptions:
			values[i] = new([]byte)
		case aiimage.FieldID, aiimage.FieldUserID, aiimage.FieldModelID, aiimage.FieldWidth, aiimage.FieldHeight:
			values[i] = new(sql.NullInt64)
		case aiimage.FieldPlatform, aiimage.FieldModel, aiimage.FieldPrompt, aiimage.FieldStatus, aiimage.FieldPicURL, aiimage.FieldTaskID, aiimage.FieldButtons:
			values[i] = new(sql.NullString)
		case aiimage.FieldCreatedAt, aiimage.FieldUpdatedAt, aiimage.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AiImage fields.
func (_m *AiImage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aiimage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case aiimage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case aiimage.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case aiimage.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case aiimage.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case aiimage.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case aiimage.FieldModelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = int(value.Int64)
			}
		case aiimage.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case aiimage.FieldPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt", values[i])
			} else if value.Valid {
				_m.Prompt = value.String
			}
		case aiimage.FieldWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field width", values[i])
			} else if value.Valid {
				_m.Width = int(value.Int64)
			}
		case aiimage.FieldHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value.Valid {
				_m.Height = int(value.Int64)
			}
		case aiimage.FieldOptions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field options", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Options); err != nil {
					return fmt.Errorf("unmarshal field options: %w", err)
				}
			}
		case aiimage.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = types.ImageStatus(value.String)
			}
		case aiimage.FieldPicURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pic_url", values[i])
			} else if value.Valid {
				_m.PicURL = value.String
			}
		case aiimage.FieldTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = value.String
			}
		case aiimage.FieldButtons:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field buttons", values[i])
			} else if value.Valid {
				_m.Buttons = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AiImage.
// This includes values selected through modifiers, order, etc.
func (_m *AiImage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AiImage.
// Note that you need to call AiImage.Unwrap() before calling this method if this AiImage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AiImage) Update() *AiImageUpdateOne {
	return NewAiImageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AiImage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AiImage) Unwrap() *AiImage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AiImage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AiImage) String() string {
	var builder strings.Builder
	builder.WriteString("AiImage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelID))
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("prompt=")
	builder.WriteString(_m.Prompt)
	builder.WriteString(", ")
	builder.WriteString("width=")
	builder.WriteString(fmt.Sprintf("%v", _m.Width))
	builder.WriteString(", ")
	builder.WriteString("height=")
	builder.WriteString(fmt.Sprintf("%v", _m.Height))
	builder.WriteString(", ")
	builder.WriteString("options=")
	builder.WriteString(fmt.Sprintf("%v", _m.Options))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("pic_url=")
	builder.WriteString(_m.PicURL)
	builder.WriteString(", ")
	builder.WriteString("task_id=")
	builder.WriteString(_m.TaskID)
	builder.WriteString(", ")
	builder.WriteString("buttons=")
	builder.WriteString(_m.Buttons)
	builder.WriteByte(')')
	return builder.String()
}

// AiImages is a parsable slice of AiImage.
type AiImages []*AiImage
