// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ai/ent/aiknowledgedocument"
	"ai/ent/aiknowledgesegment"
	"ai/ent/predicate"
	"context"
	"entmodule"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AiKnowledgeSegmentUpdate is the builder for updating AiKnowledgeSegment entities.
type AiKnowledgeSegmentUpdate struct {
	config
	hooks    []Hook
	mutation *AiKnowledgeSegmentMutation
}

// Where appends a list predicates to the AiKnowledgeSegmentUpdate builder.
func (_u *AiKnowledgeSegmentUpdate) Where(ps ...predicate.AiKnowledgeSegment) *AiKnowledgeSegmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AiKnowledgeSegmentUpdate) SetUpdatedAt(v time.Time) *AiKnowledgeSegmentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AiKnowledgeSegmentUpdate) SetDeletedAt(v time.Time) *AiKnowledgeSegmentUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AiKnowledgeSegmentUpdate) SetNillableDeletedAt(v *time.Time) *AiKnowledgeSegmentUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AiKnowledgeSegmentUpdate) ClearDeletedAt() *AiKnowledgeSegmentUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDocumentID sets the "document_id" field.
func (_u *AiKnowledgeSegmentUpdate) SetDocumentID(v int) *AiKnowledgeSegmentUpdate {
	_u.mutation.SetDocumentID(v)
	return _u
}

// SetNillableDocumentID sets the "document_id" field if the given value is not nil.
func (_u *AiKnowledgeSegmentUpdate) SetNillableDocumentID(v *int) *AiKnowledgeSegmentUpdate {
	if v != nil {
		_u.SetDocumentID(*v)
	}
	return _u
}

// SetKnowledgeID sets the "knowledge_id" field.
func (_u *AiKnowledgeSegmentUpdate) SetKnowledgeID(v int) *AiKnowledgeSegmentUpdate {
	_u.mutation.ResetKnowledgeID()
	_u.mutation.SetKnowledgeID(v)
	return _u
}

// SetNillableKnowledgeID sets the "knowledge_id" field if the given value is not nil.
func (_u *AiKnowledgeSegmentUpdate) SetNillableKnowledgeID(v *int) *AiKnowledgeSegmentUpdate {
	if v != nil {
		_u.SetKnowledgeID(*v)
	}
	return _u
}

// AddKnowledgeID adds value to the "knowledge_id" field.
func (_u *AiKnowledgeSegmentUpdate) AddKnowledgeID(v int) *AiKnowledgeSegmentUpdate {
	_u.mutation.AddKnowledgeID(v)
	return _u
}

// SetContentLength sets the "content_length" field.
func (_u *AiKnowledgeSegmentUpdate) SetContentLength(v int) *AiKnowledgeSegmentUpdate {
	_u.mutation.ResetContentLength()
	_u.mutation.SetContentLength(v)
	return _u
}

// SetNillableContentLength sets the "content_length" field if the given value is not nil.
func (_u *AiKnowledgeSegmentUpdate) SetNillableContentLength(v *int) *AiKnowledgeSegmentUpdate {
	if v != nil {
		_u.SetContentLength(*v)
	}
	return _u
}

// AddContentLength adds value to the "content_length" field.
func (_u *AiKnowledgeSegmentUpdate) AddContentLength(v int) *AiKnowledgeSegmentUpdate {
	_u.mutation.AddContentLength(v)
	return _u
}

// SetTokens sets the "tokens" field.
func (_u *AiKnowledgeSegmentUpdate) SetTokens(v int) *AiKnowledgeSegmentUpdate {
	_u.mutation.ResetTokens()
	_u.mutation.SetTokens(v)
	return _u
}

// SetNillableTokens sets the "tokens" field if the given value is not nil.
func (_u *AiKnowledgeSegmentUpdate) SetNillableTokens(v *int) *AiKnowledgeSegmentUpdate {
	if v != nil {
		_u.SetTokens(*v)
	}
	return _u
}

// AddTokens adds value to the "tokens" field.
func (_u *AiKnowledgeSegmentUpdate) AddTokens(v int) *AiKnowledgeSegmentUpdate {
	_u.mutation.AddTokens(v)
	return _u
}

// SetVectorID sets the "vector_id" field.
func (_u *AiKnowledgeSegmentUpdate) SetVectorID(v string) *AiKnowledgeSegmentUpdate {
	_u.mutation.SetVectorID(v)
	return _u
}

// SetNillableVectorID sets the "vector_id" field if the given value is not nil.
func (_u *AiKnowledgeSegmentUpdate) SetNillableVectorID(v *string) *AiKnowledgeSegmentUpdate {
	if v != nil {
		_u.SetVectorID(*v)
	}
	return _u
}

// SetRetrievalCount sets the "retrieval_count" field.
func (_u *AiKnowledgeSegmentUpdate) SetRetrievalCount(v int) *AiKnowledgeSegmentUpdate {
	_u.mutation.ResetRetrievalCount()
	_u.mutation.SetRetrievalCount(v)
	return _u
}

// SetNillableRetrievalCount sets the "retrieval_count" field if the given value is not nil.
func (_u *AiKnowledgeSegmentUpdate) SetNillableRetrievalCount(v *int) *AiKnowledgeSegmentUpdate {
	if v != nil {
		_u.SetRetrievalCount(*v)
	}
	return _u
}

// AddRetrievalCount adds value to the "retrieval_count" field.
func (_u *AiKnowledgeSegmentUpdate) AddRetrievalCount(v int) *AiKnowledgeSegmentUpdate {
	_u.mutation.AddRetrievalCount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AiKnowledgeSegmentUpdate) SetStatus(v entmodule.Status) *AiKnowledgeSegmentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AiKnowledgeSegmentUpdate) SetNillableStatus(v *entmodule.Status) *AiKnowledgeSegmentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAiKnowledgeDocumentID sets the "ai_knowledge_document" edge to the AiKnowledgeDocument entity by ID.
func (_u *AiKnowledgeSegmentUpdate) SetAiKnowledgeDocumentID(id int) *AiKnowledgeSegmentUpdate {
	_u.mutation.SetAiKnowledgeDocumentID(id)
	return _u
}

// SetAiKnowledgeDocument sets the "ai_knowledge_document" edge to the AiKnowledgeDocument entity.
func (_u *AiKnowledgeSegmentUpdate) SetAiKnowledgeDocument(v *AiKnowledgeDocument) *AiKnowledgeSegmentUpdate {
	return _u.SetAiKnowledgeDocumentID(v.ID)
}

// Mutation returns the AiKnowledgeSegmentMutation object of the builder.
func (_u *AiKnowledgeSegmentUpdate) Mutation() *AiKnowledgeSegmentMutation {
	return _u.mutation
}

// ClearAiKnowledgeDocument clears the "ai_knowledge_document" edge to the AiKnowledgeDocument entity.
func (_u *AiKnowledgeSegmentUpdate) ClearAiKnowledgeDocument() *AiKnowledgeSegmentUpdate {
	_u.mutation.ClearAiKnowledgeDocument()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AiKnowledgeSegmentUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AiKnowledgeSegmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AiKnowledgeSegmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AiKnowledgeSegmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AiKnowledgeSegmentUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if aiknowledgesegment.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized aiknowledgesegment.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := aiknowledgesegment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AiKnowledgeSegmentUpdate) check() error {
	if v, ok := _u.mutation.VectorID(); ok {
		if err := aiknowledgesegment.VectorIDValidator(v); err != nil {
			return &ValidationError{Name: "vector_id", err: fmt.Errorf(`ent: validator failed for field "AiKnowledgeSegment.vector_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := aiknowledgesegment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AiKnowledgeSegment.status": %w`, err)}
		}
	}
	if _u.mutation.AiKnowledgeDocumentCleared() && len(_u.mutation.AiKnowledgeDocumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AiKnowledgeSegment.ai_knowledge_document"`)
	}
	return nil
}

func (_u *AiKnowledgeSegmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aiknowledgesegment.Table, aiknowledgesegment.Columns, sqlgraph.NewFieldSpec(aiknowledgesegment.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aiknowledgesegment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(aiknowledgesegment.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(aiknowledgesegment.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.KnowledgeID(); ok {
		_spec.SetField(aiknowledgesegment.FieldKnowledgeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedKnowledgeID(); ok {
		_spec.AddField(aiknowledgesegment.FieldKnowledgeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ContentLength(); ok {
		_spec.SetField(aiknowledgesegment.FieldContentLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedContentLength(); ok {
		_spec.AddField(aiknowledgesegment.FieldContentLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Tokens(); ok {
		_spec.SetField(aiknowledgesegment.FieldTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokens(); ok {
		_spec.AddField(aiknowledgesegment.FieldTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VectorID(); ok {
		_spec.SetField(aiknowledgesegment.FieldVectorID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RetrievalCount(); ok {
		_spec.SetField(aiknowledgesegment.FieldRetrievalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetrievalCount(); ok {
		_spec.AddField(aiknowledgesegment.FieldRetrievalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(aiknowledgesegment.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.AiKnowledgeDocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aiknowledgesegment.AiKnowledgeDocumentTable,
			Columns: []string{aiknowledgesegment.AiKnowledgeDocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aiknowledgedocument.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AiKnowledgeDocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aiknowledgesegment.AiKnowledgeDocumentTable,
			Columns: []string{aiknowledgesegment.AiKnowledgeDocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aiknowledgedocument.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aiknowledgesegment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AiKnowledgeSegmentUpdateOne is the builder for updating a single AiKnowledgeSegment entity.
type AiKnowledgeSegmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AiKnowledgeSegmentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AiKnowledgeSegmentUpdateOne) SetUpdatedAt(v time.Time) *AiKnowledgeSegmentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AiKnowledgeSegmentUpdateOne) SetDeletedAt(v time.Time) *AiKnowledgeSegmentUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AiKnowledgeSegmentUpdateOne) SetNillableDeletedAt(v *time.Time) *AiKnowledgeSegmentUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AiKnowledgeSegmentUpdateOne) ClearDeletedAt() *AiKnowledgeSegmentUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDocumentID sets the "document_id" field.
func (_u *AiKnowledgeSegmentUpdateOne) SetDocumentID(v int) *AiKnowledgeSegmentUpdateOne {
	_u.mutation.SetDocumentID(v)
	return _u
}

// SetNillableDocumentID sets the "document_id" field if the given value is not nil.
func (_u *AiKnowledgeSegmentUpdateOne) SetNillableDocumentID(v *int) *AiKnowledgeSegmentUpdateOne {
	if v != nil {
		_u.SetDocumentID(*v)
	}
	return _u
}

// SetKnowledgeID sets the "knowledge_id" field.
func (_u *AiKnowledgeSegmentUpdateOne) SetKnowledgeID(v int) *AiKnowledgeSegmentUpdateOne {
	_u.mutation.ResetKnowledgeID()
	_u.mutation.SetKnowledgeID(v)
	return _u
}

// SetNillableKnowledgeID sets the "knowledge_id" field if the given value is not nil.
func (_u *AiKnowledgeSegmentUpdateOne) SetNillableKnowledgeID(v *int) *AiKnowledgeSegmentUpdateOne {
	if v != nil {
		_u.SetKnowledgeID(*v)
	}
	return _u
}

// AddKnowledgeID adds value to the "knowledge_id" field.
func (_u *AiKnowledgeSegmentUpdateOne) AddKnowledgeID(v int) *AiKnowledgeSegmentUpdateOne {
	_u.mutation.AddKnowledgeID(v)
	return _u
}

// SetContentLength sets the "content_length" field.
func (_u *AiKnowledgeSegmentUpdateOne) SetContentLength(v int) *AiKnowledgeSegmentUpdateOne {
	_u.mutation.ResetContentLength()
	_u.mutation.SetContentLength(v)
	return _u
}

// SetNillableContentLength sets the "content_length" field if the given value is not nil.
func (_u *AiKnowledgeSegmentUpdateOne) SetNillableContentLength(v *int) *AiKnowledgeSegmentUpdateOne {
	if v != nil {
		_u.SetContentLength(*v)
	}
	return _u
}

// AddContentLength adds value to the "content_length" field.
func (_u *AiKnowledgeSegmentUpdateOne) AddContentLength(v int) *AiKnowledgeSegmentUpdateOne {
	_u.mutation.AddContentLength(v)
	return _u
}

// SetTokens sets the "tokens" field.
func (_u *AiKnowledgeSegmentUpdateOne) SetTokens(v int) *AiKnowledgeSegmentUpdateOne {
	_u.mutation.ResetTokens()
	_u.mutation.SetTokens(v)
	return _u
}

// SetNillableTokens sets the "tokens" field if the given value is not nil.
func (_u *AiKnowledgeSegmentUpdateOne) SetNillableTokens(v *int) *AiKnowledgeSegmentUpdateOne {
	if v != nil {
		_u.SetTokens(*v)
	}
	return _u
}

// AddTokens adds value to the "tokens" field.
func (_u *AiKnowledgeSegmentUpdateOne) AddTokens(v int) *AiKnowledgeSegmentUpdateOne {
	_u.mutation.AddTokens(v)
	return _u
}

// SetVectorID sets the "vector_id" field.
func (_u *AiKnowledgeSegmentUpdateOne) SetVectorID(v string) *AiKnowledgeSegmentUpdateOne {
	_u.mutation.SetVectorID(v)
	return _u
}

// SetNillableVectorID sets the "vector_id" field if the given value is not nil.
func (_u *AiKnowledgeSegmentUpdateOne) SetNillableVectorID(v *string) *AiKnowledgeSegmentUpdateOne {
	if v != nil {
		_u.SetVectorID(*v)
	}
	return _u
}

// SetRetrievalCount sets the "retrieval_count" field.
func (_u *AiKnowledgeSegmentUpdateOne) SetRetrievalCount(v int) *AiKnowledgeSegmentUpdateOne {
	_u.mutation.ResetRetrievalCount()
	_u.mutation.SetRetrievalCount(v)
	return _u
}

// SetNillableRetrievalCount sets the "retrieval_count" field if the given value is not nil.
func (_u *AiKnowledgeSegmentUpdateOne) SetNillableRetrievalCount(v *int) *AiKnowledgeSegmentUpdateOne {
	if v != nil {
		_u.SetRetrievalCount(*v)
	}
	return _u
}

// AddRetrievalCount adds value to the "retrieval_count" field.
func (_u *AiKnowledgeSegmentUpdateOne) AddRetrievalCount(v int) *AiKnowledgeSegmentUpdateOne {
	_u.mutation.AddRetrievalCount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AiKnowledgeSegmentUpdateOne) SetStatus(v entmodule.Status) *AiKnowledgeSegmentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AiKnowledgeSegmentUpdateOne) SetNillableStatus(v *entmodule.Status) *AiKnowledgeSegmentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAiKnowledgeDocumentID sets the "ai_knowledge_document" edge to the AiKnowledgeDocument entity by ID.
func (_u *AiKnowledgeSegmentUpdateOne) SetAiKnowledgeDocumentID(id int) *AiKnowledgeSegmentUpdateOne {
	_u.mutation.SetAiKnowledgeDocumentID(id)
	return _u
}

// SetAiKnowledgeDocument sets the "ai_knowledge_document" edge to the AiKnowledgeDocument entity.
func (_u *AiKnowledgeSegmentUpdateOne) SetAiKnowledgeDocument(v *AiKnowledgeDocument) *AiKnowledgeSegmentUpdateOne {
	return _u.SetAiKnowledgeDocumentID(v.ID)
}

// Mutation returns the AiKnowledgeSegmentMutation object of the builder.
func (_u *AiKnowledgeSegmentUpdateOne) Mutation() *AiKnowledgeSegmentMutation {
	return _u.mutation
}

// ClearAiKnowledgeDocument clears the "ai_knowledge_document" edge to the AiKnowledgeDocument entity.
func (_u *AiKnowledgeSegmentUpdateOne) ClearAiKnowledgeDocument() *AiKnowledgeSegmentUpdateOne {
	_u.mutation.ClearAiKnowledgeDocument()
	return _u
}

// Where appends a list predicates to the AiKnowledgeSegmentUpdate builder.
func (_u *AiKnowledgeSegmentUpdateOne) Where(ps ...predicate.AiKnowledgeSegment) *AiKnowledgeSegmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AiKnowledgeSegmentUpdateOne) Select(field string, fields ...string) *AiKnowledgeSegmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AiKnowledgeSegment entity.
func (_u *AiKnowledgeSegmentUpdateOne) Save(ctx context.Context) (*AiKnowledgeSegment, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AiKnowledgeSegmentUpdateOne) SaveX(ctx context.Context) *AiKnowledgeSegment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AiKnowledgeSegmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AiKnowledgeSegmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AiKnowledgeSegmentUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if aiknowledgesegment.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized aiknowledgesegment.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := aiknowledgesegment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AiKnowledgeSegmentUpdateOne) check() error {
	if v, ok := _u.mutation.VectorID(); ok {
		if err := aiknowledgesegment.VectorIDValidator(v); err != nil {
			return &ValidationError{Name: "vector_id", err: fmt.Errorf(`ent: validator failed for field "AiKnowledgeSegment.vector_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := aiknowledgesegment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AiKnowledgeSegment.status": %w`, err)}
		}
	}
	if _u.mutation.AiKnowledgeDocumentCleared() && len(_u.mutation.AiKnowledgeDocumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AiKnowledgeSegment.ai_knowledge_document"`)
	}
	return nil
}

func (_u *AiKnowledgeSegmentUpdateOne) sqlSave(ctx context.Context) (_node *AiKnowledgeSegment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aiknowledgesegment.Table, aiknowledgesegment.Columns, sqlgraph.NewFieldSpec(aiknowledgesegment.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AiKnowledgeSegment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aiknowledgesegment.FieldID)
		for _, f := range fields {
			if !aiknowledgesegment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aiknowledgesegment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aiknowledgesegment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(aiknowledgesegment.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(aiknowledgesegment.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.KnowledgeID(); ok {
		_spec.SetField(aiknowledgesegment.FieldKnowledgeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedKnowledgeID(); ok {
		_spec.AddField(aiknowledgesegment.FieldKnowledgeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ContentLength(); ok {
		_spec.SetField(aiknowledgesegment.FieldContentLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedContentLength(); ok {
		_spec.AddField(aiknowledgesegment.FieldContentLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Tokens(); ok {
		_spec.SetField(aiknowledgesegment.FieldTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokens(); ok {
		_spec.AddField(aiknowledgesegment.FieldTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VectorID(); ok {
		_spec.SetField(aiknowledgesegment.FieldVectorID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RetrievalCount(); ok {
		_spec.SetField(aiknowledgesegment.FieldRetrievalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetrievalCount(); ok {
		_spec.AddField(aiknowledgesegment.FieldRetrievalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(aiknowledgesegment.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.AiKnowledgeDocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aiknowledgesegment.AiKnowledgeDocumentTable,
			Columns: []string{aiknowledgesegment.AiKnowledgeDocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aiknowledgedocument.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AiKnowledgeDocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aiknowledgesegment.AiKnowledgeDocumentTable,
			Columns: []string{aiknowledgesegment.AiKnowledgeDocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aiknowledgedocument.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AiKnowledgeSegment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aiknowledgesegment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
