// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v5.29.3
// source: ai/admin/v1/admin.proto

package v1

import (
	v1 "api/api/ai/common/v1"
	v11 "api/api/common/v1"
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAdminBatchDeleteApiKey = "/ai.admin.v1.Admin/BatchDeleteApiKey"
const OperationAdminBatchDeleteImage = "/ai.admin.v1.Admin/BatchDeleteImage"
const OperationAdminBatchDeleteKnowledgeDocument = "/ai.admin.v1.Admin/BatchDeleteKnowledgeDocument"
const OperationAdminBatchDeleteModel = "/ai.admin.v1.Admin/BatchDeleteModel"
const OperationAdminBatchDeleteRole = "/ai.admin.v1.Admin/BatchDeleteRole"
const OperationAdminCreateApikey = "/ai.admin.v1.Admin/CreateApikey"
const OperationAdminCreateModel = "/ai.admin.v1.Admin/CreateModel"
const OperationAdminCreateRole = "/ai.admin.v1.Admin/CreateRole"
const OperationAdminDeleteApikey = "/ai.admin.v1.Admin/DeleteApikey"
const OperationAdminDeleteKnowledge = "/ai.admin.v1.Admin/DeleteKnowledge"
const OperationAdminDeleteKnowledgeDocument = "/ai.admin.v1.Admin/DeleteKnowledgeDocument"
const OperationAdminDeleteModel = "/ai.admin.v1.Admin/DeleteModel"
const OperationAdminGetApikey = "/ai.admin.v1.Admin/GetApikey"
const OperationAdminGetKnowledge = "/ai.admin.v1.Admin/GetKnowledge"
const OperationAdminGetKnowledgeDocument = "/ai.admin.v1.Admin/GetKnowledgeDocument"
const OperationAdminGetKnowledgeSegment = "/ai.admin.v1.Admin/GetKnowledgeSegment"
const OperationAdminGetModel = "/ai.admin.v1.Admin/GetModel"
const OperationAdminGetRole = "/ai.admin.v1.Admin/GetRole"
const OperationAdminListApikey = "/ai.admin.v1.Admin/ListApikey"
const OperationAdminListImage = "/ai.admin.v1.Admin/ListImage"
const OperationAdminListKnowledge = "/ai.admin.v1.Admin/ListKnowledge"
const OperationAdminListKnowledgeDocument = "/ai.admin.v1.Admin/ListKnowledgeDocument"
const OperationAdminListKnowledgeSegments = "/ai.admin.v1.Admin/ListKnowledgeSegments"
const OperationAdminListModel = "/ai.admin.v1.Admin/ListModel"
const OperationAdminListRole = "/ai.admin.v1.Admin/ListRole"
const OperationAdminUpdateApikey = "/ai.admin.v1.Admin/UpdateApikey"
const OperationAdminUpdateDocumentStatus = "/ai.admin.v1.Admin/UpdateDocumentStatus"
const OperationAdminUpdateImagePublicStatus = "/ai.admin.v1.Admin/UpdateImagePublicStatus"
const OperationAdminUpdateModel = "/ai.admin.v1.Admin/UpdateModel"

type AdminHTTPServer interface {
	BatchDeleteApiKey(context.Context, *BatchDeleteRequest) (*emptypb.Empty, error)
	BatchDeleteImage(context.Context, *BatchDeleteRequest) (*emptypb.Empty, error)
	BatchDeleteKnowledgeDocument(context.Context, *BatchDeleteRequest) (*emptypb.Empty, error)
	BatchDeleteModel(context.Context, *BatchDeleteRequest) (*emptypb.Empty, error)
	BatchDeleteRole(context.Context, *BatchDeleteRoleRequest) (*emptypb.Empty, error)
	// CreateApikey Api Key
	CreateApikey(context.Context, *v1.AiApiKey) (*v1.AiApiKey, error)
	// CreateModel Model
	CreateModel(context.Context, *v1.AiModel) (*v1.AiModel, error)
	// CreateRole Role
	CreateRole(context.Context, *v1.AiChatRole) (*v1.AiChatRole, error)
	DeleteApikey(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	// DeleteKnowledge Knowledge
	DeleteKnowledge(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	// DeleteKnowledgeDocument Knowledge Document
	DeleteKnowledgeDocument(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	DeleteModel(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	GetApikey(context.Context, *SimpleRequest) (*v1.AiApiKey, error)
	GetKnowledge(context.Context, *SimpleRequest) (*v1.AiKnowledge, error)
	GetKnowledgeDocument(context.Context, *SimpleRequest) (*v1.AiKnowledgeDocument, error)
	// GetKnowledgeSegment Knowledge Document Segment
	GetKnowledgeSegment(context.Context, *SimpleRequest) (*v1.AiKnowledgeSegment, error)
	GetModel(context.Context, *SimpleRequest) (*v1.AiModel, error)
	GetRole(context.Context, *SimpleRequest) (*v1.AiChatRole, error)
	ListApikey(context.Context, *v11.ListRequest) (*ListApikeyResponse, error)
	// ListImage Image
	ListImage(context.Context, *v11.ListRequest) (*ListImageResponse, error)
	ListKnowledge(context.Context, *v11.ListRequest) (*ListKnowledgeResponse, error)
	ListKnowledgeDocument(context.Context, *v11.ListRequest) (*ListKnowledgeDocumentResponse, error)
	ListKnowledgeSegments(context.Context, *v11.ListRequest) (*ListKnowledgeSegmentResponse, error)
	ListModel(context.Context, *v11.ListRequest) (*ListModelResponse, error)
	ListRole(context.Context, *v11.ListRequest) (*ListRoleResponse, error)
	UpdateApikey(context.Context, *v1.AiApiKey) (*v1.AiApiKey, error)
	UpdateDocumentStatus(context.Context, *UpdateDocumentStatusRequest) (*v1.AiKnowledgeDocument, error)
	UpdateImagePublicStatus(context.Context, *UpdateImageStatusRequest) (*v1.AiImage, error)
	UpdateModel(context.Context, *v1.AiModel) (*v1.AiModel, error)
}

func RegisterAdminHTTPServer(s *http.Server, srv AdminHTTPServer) {
	r := s.Route("/")
	r.POST("/admin/ai/api-key", _Admin_CreateApikey0_HTTP_Handler(srv))
	r.PUT("/admin/ai/api-key/{id}", _Admin_UpdateApikey0_HTTP_Handler(srv))
	r.DELETE("/admin/ai/api-key/{id}", _Admin_DeleteApikey0_HTTP_Handler(srv))
	r.GET("/admin/ai/api-key/{id}", _Admin_GetApikey0_HTTP_Handler(srv))
	r.GET("/admin/ai/api-key/list", _Admin_ListApikey0_HTTP_Handler(srv))
	r.POST("/admin/admin/ai/api_key/batch/delete", _Admin_BatchDeleteApiKey0_HTTP_Handler(srv))
	r.POST("/admin/ai/model", _Admin_CreateModel0_HTTP_Handler(srv))
	r.PUT("/admin/ai/model/{id}", _Admin_UpdateModel0_HTTP_Handler(srv))
	r.DELETE("/admin/ai/model/{id}", _Admin_DeleteModel0_HTTP_Handler(srv))
	r.GET("/admin/ai/model/{id}", _Admin_GetModel0_HTTP_Handler(srv))
	r.GET("/admin/ai/model/list", _Admin_ListModel0_HTTP_Handler(srv))
	r.POST("/admin/ai/model/batch/delete", _Admin_BatchDeleteModel0_HTTP_Handler(srv))
	r.POST("/admin/ai/role", _Admin_CreateRole0_HTTP_Handler(srv))
	r.GET("/admin/ai/role/{id}", _Admin_GetRole0_HTTP_Handler(srv))
	r.GET("/admin/ai/role/list", _Admin_ListRole0_HTTP_Handler(srv))
	r.POST("/admin/ai/role/batch/delete", _Admin_BatchDeleteRole0_HTTP_Handler(srv))
	r.DELETE("/admin/ai/knowledge/{id}", _Admin_DeleteKnowledge0_HTTP_Handler(srv))
	r.GET("/admin/ai/knowledge/{id}", _Admin_GetKnowledge0_HTTP_Handler(srv))
	r.GET("/admin/ai/knowledge/list", _Admin_ListKnowledge0_HTTP_Handler(srv))
	r.DELETE("/admin/ai/knowledge/document/{id}", _Admin_DeleteKnowledgeDocument0_HTTP_Handler(srv))
	r.POST("/admin/ai/knowledge/document/delete", _Admin_BatchDeleteKnowledgeDocument0_HTTP_Handler(srv))
	r.GET("/admin/ai/knowledge/document/{id}", _Admin_GetKnowledgeDocument0_HTTP_Handler(srv))
	r.GET("/admin/ai/knowledge/document/list", _Admin_ListKnowledgeDocument0_HTTP_Handler(srv))
	r.PUT("/admin/ai/knowledge/document/{id}/status", _Admin_UpdateDocumentStatus0_HTTP_Handler(srv))
	r.GET("/admin/ai/knowledge/segment/{id}", _Admin_GetKnowledgeSegment0_HTTP_Handler(srv))
	r.GET("/admin/ai/knowledge/segment/list", _Admin_ListKnowledgeSegments0_HTTP_Handler(srv))
	r.GET("/admin/ai/image/list", _Admin_ListImage0_HTTP_Handler(srv))
	r.PUT("/admin/ai/image/{id}/public", _Admin_UpdateImagePublicStatus0_HTTP_Handler(srv))
	r.POST("/admin/ai/image/delete", _Admin_BatchDeleteImage0_HTTP_Handler(srv))
}

func _Admin_CreateApikey0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.AiApiKey
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminCreateApikey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateApikey(ctx, req.(*v1.AiApiKey))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.AiApiKey)
		return ctx.Result(200, reply)
	}
}

func _Admin_UpdateApikey0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.AiApiKey
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminUpdateApikey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateApikey(ctx, req.(*v1.AiApiKey))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.AiApiKey)
		return ctx.Result(200, reply)
	}
}

func _Admin_DeleteApikey0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminDeleteApikey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteApikey(ctx, req.(*DeleteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Admin_GetApikey0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SimpleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminGetApikey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetApikey(ctx, req.(*SimpleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.AiApiKey)
		return ctx.Result(200, reply)
	}
}

func _Admin_ListApikey0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v11.ListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminListApikey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListApikey(ctx, req.(*v11.ListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListApikeyResponse)
		return ctx.Result(200, reply)
	}
}

func _Admin_BatchDeleteApiKey0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchDeleteRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminBatchDeleteApiKey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchDeleteApiKey(ctx, req.(*BatchDeleteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Admin_CreateModel0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.AiModel
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminCreateModel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateModel(ctx, req.(*v1.AiModel))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.AiModel)
		return ctx.Result(200, reply)
	}
}

func _Admin_UpdateModel0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.AiModel
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminUpdateModel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateModel(ctx, req.(*v1.AiModel))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.AiModel)
		return ctx.Result(200, reply)
	}
}

func _Admin_DeleteModel0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminDeleteModel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteModel(ctx, req.(*DeleteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Admin_GetModel0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SimpleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminGetModel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetModel(ctx, req.(*SimpleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.AiModel)
		return ctx.Result(200, reply)
	}
}

func _Admin_ListModel0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v11.ListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminListModel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListModel(ctx, req.(*v11.ListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListModelResponse)
		return ctx.Result(200, reply)
	}
}

func _Admin_BatchDeleteModel0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchDeleteRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminBatchDeleteModel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchDeleteModel(ctx, req.(*BatchDeleteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Admin_CreateRole0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.AiChatRole
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminCreateRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateRole(ctx, req.(*v1.AiChatRole))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.AiChatRole)
		return ctx.Result(200, reply)
	}
}

func _Admin_GetRole0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SimpleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminGetRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRole(ctx, req.(*SimpleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.AiChatRole)
		return ctx.Result(200, reply)
	}
}

func _Admin_ListRole0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v11.ListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminListRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRole(ctx, req.(*v11.ListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRoleResponse)
		return ctx.Result(200, reply)
	}
}

func _Admin_BatchDeleteRole0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchDeleteRoleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminBatchDeleteRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchDeleteRole(ctx, req.(*BatchDeleteRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Admin_DeleteKnowledge0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminDeleteKnowledge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteKnowledge(ctx, req.(*DeleteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Admin_GetKnowledge0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SimpleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminGetKnowledge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetKnowledge(ctx, req.(*SimpleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.AiKnowledge)
		return ctx.Result(200, reply)
	}
}

func _Admin_ListKnowledge0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v11.ListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminListKnowledge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListKnowledge(ctx, req.(*v11.ListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListKnowledgeResponse)
		return ctx.Result(200, reply)
	}
}

func _Admin_DeleteKnowledgeDocument0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminDeleteKnowledgeDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteKnowledgeDocument(ctx, req.(*DeleteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Admin_BatchDeleteKnowledgeDocument0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchDeleteRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminBatchDeleteKnowledgeDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchDeleteKnowledgeDocument(ctx, req.(*BatchDeleteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Admin_GetKnowledgeDocument0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SimpleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminGetKnowledgeDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetKnowledgeDocument(ctx, req.(*SimpleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.AiKnowledgeDocument)
		return ctx.Result(200, reply)
	}
}

func _Admin_ListKnowledgeDocument0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v11.ListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminListKnowledgeDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListKnowledgeDocument(ctx, req.(*v11.ListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListKnowledgeDocumentResponse)
		return ctx.Result(200, reply)
	}
}

func _Admin_UpdateDocumentStatus0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateDocumentStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminUpdateDocumentStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateDocumentStatus(ctx, req.(*UpdateDocumentStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.AiKnowledgeDocument)
		return ctx.Result(200, reply)
	}
}

func _Admin_GetKnowledgeSegment0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SimpleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminGetKnowledgeSegment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetKnowledgeSegment(ctx, req.(*SimpleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.AiKnowledgeSegment)
		return ctx.Result(200, reply)
	}
}

func _Admin_ListKnowledgeSegments0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v11.ListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminListKnowledgeSegments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListKnowledgeSegments(ctx, req.(*v11.ListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListKnowledgeSegmentResponse)
		return ctx.Result(200, reply)
	}
}

func _Admin_ListImage0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v11.ListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminListImage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListImage(ctx, req.(*v11.ListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListImageResponse)
		return ctx.Result(200, reply)
	}
}

func _Admin_UpdateImagePublicStatus0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateImageStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminUpdateImagePublicStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateImagePublicStatus(ctx, req.(*UpdateImageStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.AiImage)
		return ctx.Result(200, reply)
	}
}

func _Admin_BatchDeleteImage0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchDeleteRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminBatchDeleteImage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchDeleteImage(ctx, req.(*BatchDeleteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type AdminHTTPClient interface {
	BatchDeleteApiKey(ctx context.Context, req *BatchDeleteRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	BatchDeleteImage(ctx context.Context, req *BatchDeleteRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	BatchDeleteKnowledgeDocument(ctx context.Context, req *BatchDeleteRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	BatchDeleteModel(ctx context.Context, req *BatchDeleteRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	BatchDeleteRole(ctx context.Context, req *BatchDeleteRoleRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// CreateApikey Api Key
	CreateApikey(ctx context.Context, req *v1.AiApiKey, opts ...http.CallOption) (rsp *v1.AiApiKey, err error)
	// CreateModel Model
	CreateModel(ctx context.Context, req *v1.AiModel, opts ...http.CallOption) (rsp *v1.AiModel, err error)
	// CreateRole Role
	CreateRole(ctx context.Context, req *v1.AiChatRole, opts ...http.CallOption) (rsp *v1.AiChatRole, err error)
	DeleteApikey(ctx context.Context, req *DeleteRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// DeleteKnowledge Knowledge
	DeleteKnowledge(ctx context.Context, req *DeleteRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// DeleteKnowledgeDocument Knowledge Document
	DeleteKnowledgeDocument(ctx context.Context, req *DeleteRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteModel(ctx context.Context, req *DeleteRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetApikey(ctx context.Context, req *SimpleRequest, opts ...http.CallOption) (rsp *v1.AiApiKey, err error)
	GetKnowledge(ctx context.Context, req *SimpleRequest, opts ...http.CallOption) (rsp *v1.AiKnowledge, err error)
	GetKnowledgeDocument(ctx context.Context, req *SimpleRequest, opts ...http.CallOption) (rsp *v1.AiKnowledgeDocument, err error)
	// GetKnowledgeSegment Knowledge Document Segment
	GetKnowledgeSegment(ctx context.Context, req *SimpleRequest, opts ...http.CallOption) (rsp *v1.AiKnowledgeSegment, err error)
	GetModel(ctx context.Context, req *SimpleRequest, opts ...http.CallOption) (rsp *v1.AiModel, err error)
	GetRole(ctx context.Context, req *SimpleRequest, opts ...http.CallOption) (rsp *v1.AiChatRole, err error)
	ListApikey(ctx context.Context, req *v11.ListRequest, opts ...http.CallOption) (rsp *ListApikeyResponse, err error)
	// ListImage Image
	ListImage(ctx context.Context, req *v11.ListRequest, opts ...http.CallOption) (rsp *ListImageResponse, err error)
	ListKnowledge(ctx context.Context, req *v11.ListRequest, opts ...http.CallOption) (rsp *ListKnowledgeResponse, err error)
	ListKnowledgeDocument(ctx context.Context, req *v11.ListRequest, opts ...http.CallOption) (rsp *ListKnowledgeDocumentResponse, err error)
	ListKnowledgeSegments(ctx context.Context, req *v11.ListRequest, opts ...http.CallOption) (rsp *ListKnowledgeSegmentResponse, err error)
	ListModel(ctx context.Context, req *v11.ListRequest, opts ...http.CallOption) (rsp *ListModelResponse, err error)
	ListRole(ctx context.Context, req *v11.ListRequest, opts ...http.CallOption) (rsp *ListRoleResponse, err error)
	UpdateApikey(ctx context.Context, req *v1.AiApiKey, opts ...http.CallOption) (rsp *v1.AiApiKey, err error)
	UpdateDocumentStatus(ctx context.Context, req *UpdateDocumentStatusRequest, opts ...http.CallOption) (rsp *v1.AiKnowledgeDocument, err error)
	UpdateImagePublicStatus(ctx context.Context, req *UpdateImageStatusRequest, opts ...http.CallOption) (rsp *v1.AiImage, err error)
	UpdateModel(ctx context.Context, req *v1.AiModel, opts ...http.CallOption) (rsp *v1.AiModel, err error)
}

type AdminHTTPClientImpl struct {
	cc *http.Client
}

func NewAdminHTTPClient(client *http.Client) AdminHTTPClient {
	return &AdminHTTPClientImpl{client}
}

func (c *AdminHTTPClientImpl) BatchDeleteApiKey(ctx context.Context, in *BatchDeleteRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/admin/admin/ai/api_key/batch/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminBatchDeleteApiKey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) BatchDeleteImage(ctx context.Context, in *BatchDeleteRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/admin/ai/image/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminBatchDeleteImage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) BatchDeleteKnowledgeDocument(ctx context.Context, in *BatchDeleteRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/admin/ai/knowledge/document/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminBatchDeleteKnowledgeDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) BatchDeleteModel(ctx context.Context, in *BatchDeleteRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/admin/ai/model/batch/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminBatchDeleteModel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) BatchDeleteRole(ctx context.Context, in *BatchDeleteRoleRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/admin/ai/role/batch/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminBatchDeleteRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateApikey Api Key
func (c *AdminHTTPClientImpl) CreateApikey(ctx context.Context, in *v1.AiApiKey, opts ...http.CallOption) (*v1.AiApiKey, error) {
	var out v1.AiApiKey
	pattern := "/admin/ai/api-key"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminCreateApikey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateModel Model
func (c *AdminHTTPClientImpl) CreateModel(ctx context.Context, in *v1.AiModel, opts ...http.CallOption) (*v1.AiModel, error) {
	var out v1.AiModel
	pattern := "/admin/ai/model"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminCreateModel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateRole Role
func (c *AdminHTTPClientImpl) CreateRole(ctx context.Context, in *v1.AiChatRole, opts ...http.CallOption) (*v1.AiChatRole, error) {
	var out v1.AiChatRole
	pattern := "/admin/ai/role"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminCreateRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) DeleteApikey(ctx context.Context, in *DeleteRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/admin/ai/api-key/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminDeleteApikey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteKnowledge Knowledge
func (c *AdminHTTPClientImpl) DeleteKnowledge(ctx context.Context, in *DeleteRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/admin/ai/knowledge/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminDeleteKnowledge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteKnowledgeDocument Knowledge Document
func (c *AdminHTTPClientImpl) DeleteKnowledgeDocument(ctx context.Context, in *DeleteRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/admin/ai/knowledge/document/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminDeleteKnowledgeDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) DeleteModel(ctx context.Context, in *DeleteRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/admin/ai/model/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminDeleteModel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) GetApikey(ctx context.Context, in *SimpleRequest, opts ...http.CallOption) (*v1.AiApiKey, error) {
	var out v1.AiApiKey
	pattern := "/admin/ai/api-key/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminGetApikey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) GetKnowledge(ctx context.Context, in *SimpleRequest, opts ...http.CallOption) (*v1.AiKnowledge, error) {
	var out v1.AiKnowledge
	pattern := "/admin/ai/knowledge/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminGetKnowledge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) GetKnowledgeDocument(ctx context.Context, in *SimpleRequest, opts ...http.CallOption) (*v1.AiKnowledgeDocument, error) {
	var out v1.AiKnowledgeDocument
	pattern := "/admin/ai/knowledge/document/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminGetKnowledgeDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetKnowledgeSegment Knowledge Document Segment
func (c *AdminHTTPClientImpl) GetKnowledgeSegment(ctx context.Context, in *SimpleRequest, opts ...http.CallOption) (*v1.AiKnowledgeSegment, error) {
	var out v1.AiKnowledgeSegment
	pattern := "/admin/ai/knowledge/segment/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminGetKnowledgeSegment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) GetModel(ctx context.Context, in *SimpleRequest, opts ...http.CallOption) (*v1.AiModel, error) {
	var out v1.AiModel
	pattern := "/admin/ai/model/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminGetModel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) GetRole(ctx context.Context, in *SimpleRequest, opts ...http.CallOption) (*v1.AiChatRole, error) {
	var out v1.AiChatRole
	pattern := "/admin/ai/role/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminGetRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) ListApikey(ctx context.Context, in *v11.ListRequest, opts ...http.CallOption) (*ListApikeyResponse, error) {
	var out ListApikeyResponse
	pattern := "/admin/ai/api-key/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminListApikey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListImage Image
func (c *AdminHTTPClientImpl) ListImage(ctx context.Context, in *v11.ListRequest, opts ...http.CallOption) (*ListImageResponse, error) {
	var out ListImageResponse
	pattern := "/admin/ai/image/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminListImage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) ListKnowledge(ctx context.Context, in *v11.ListRequest, opts ...http.CallOption) (*ListKnowledgeResponse, error) {
	var out ListKnowledgeResponse
	pattern := "/admin/ai/knowledge/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminListKnowledge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) ListKnowledgeDocument(ctx context.Context, in *v11.ListRequest, opts ...http.CallOption) (*ListKnowledgeDocumentResponse, error) {
	var out ListKnowledgeDocumentResponse
	pattern := "/admin/ai/knowledge/document/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminListKnowledgeDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) ListKnowledgeSegments(ctx context.Context, in *v11.ListRequest, opts ...http.CallOption) (*ListKnowledgeSegmentResponse, error) {
	var out ListKnowledgeSegmentResponse
	pattern := "/admin/ai/knowledge/segment/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminListKnowledgeSegments))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) ListModel(ctx context.Context, in *v11.ListRequest, opts ...http.CallOption) (*ListModelResponse, error) {
	var out ListModelResponse
	pattern := "/admin/ai/model/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminListModel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) ListRole(ctx context.Context, in *v11.ListRequest, opts ...http.CallOption) (*ListRoleResponse, error) {
	var out ListRoleResponse
	pattern := "/admin/ai/role/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminListRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) UpdateApikey(ctx context.Context, in *v1.AiApiKey, opts ...http.CallOption) (*v1.AiApiKey, error) {
	var out v1.AiApiKey
	pattern := "/admin/ai/api-key/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminUpdateApikey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) UpdateDocumentStatus(ctx context.Context, in *UpdateDocumentStatusRequest, opts ...http.CallOption) (*v1.AiKnowledgeDocument, error) {
	var out v1.AiKnowledgeDocument
	pattern := "/admin/ai/knowledge/document/{id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminUpdateDocumentStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) UpdateImagePublicStatus(ctx context.Context, in *UpdateImageStatusRequest, opts ...http.CallOption) (*v1.AiImage, error) {
	var out v1.AiImage
	pattern := "/admin/ai/image/{id}/public"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminUpdateImagePublicStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) UpdateModel(ctx context.Context, in *v1.AiModel, opts ...http.CallOption) (*v1.AiModel, error) {
	var out v1.AiModel
	pattern := "/admin/ai/model/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminUpdateModel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
