// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: file/workflow/v1/workflow.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Workflow_ImportFiles_FullMethodName           = "/file.workflow.v1.Workflow/ImportFiles"
	Workflow_ListTasks_FullMethodName             = "/file.workflow.v1.Workflow/ListTasks"
	Workflow_GetTaskPhaseProgress_FullMethodName  = "/file.workflow.v1.Workflow/GetTaskPhaseProgress"
	Workflow_CreateArchive_FullMethodName         = "/file.workflow.v1.Workflow/CreateArchive"
	Workflow_ExtractArchive_FullMethodName        = "/file.workflow.v1.Workflow/ExtractArchive"
	Workflow_CreateRemoteDownload_FullMethodName  = "/file.workflow.v1.Workflow/CreateRemoteDownload"
	Workflow_SetDownloadTaskTarget_FullMethodName = "/file.workflow.v1.Workflow/SetDownloadTaskTarget"
	Workflow_CancelDownloadTask_FullMethodName    = "/file.workflow.v1.Workflow/CancelDownloadTask"
)

// WorkflowClient is the client API for Workflow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowClient interface {
	ImportFiles(ctx context.Context, in *ImportWorkflowRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	GetTaskPhaseProgress(ctx context.Context, in *SimpleWorkflowRequest, opts ...grpc.CallOption) (*TaskPhaseProgressResponse, error)
	CreateArchive(ctx context.Context, in *ArchiveWorkflowRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	ExtractArchive(ctx context.Context, in *ArchiveWorkflowRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	CreateRemoteDownload(ctx context.Context, in *DownloadWorkflowRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	SetDownloadTaskTarget(ctx context.Context, in *SetDownloadFilesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CancelDownloadTask(ctx context.Context, in *SimpleWorkflowRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type workflowClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowClient(cc grpc.ClientConnInterface) WorkflowClient {
	return &workflowClient{cc}
}

func (c *workflowClient) ImportFiles(ctx context.Context, in *ImportWorkflowRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, Workflow_ImportFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, Workflow_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowClient) GetTaskPhaseProgress(ctx context.Context, in *SimpleWorkflowRequest, opts ...grpc.CallOption) (*TaskPhaseProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskPhaseProgressResponse)
	err := c.cc.Invoke(ctx, Workflow_GetTaskPhaseProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowClient) CreateArchive(ctx context.Context, in *ArchiveWorkflowRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, Workflow_CreateArchive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowClient) ExtractArchive(ctx context.Context, in *ArchiveWorkflowRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, Workflow_ExtractArchive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowClient) CreateRemoteDownload(ctx context.Context, in *DownloadWorkflowRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, Workflow_CreateRemoteDownload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowClient) SetDownloadTaskTarget(ctx context.Context, in *SetDownloadFilesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Workflow_SetDownloadTaskTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowClient) CancelDownloadTask(ctx context.Context, in *SimpleWorkflowRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Workflow_CancelDownloadTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowServer is the server API for Workflow service.
// All implementations must embed UnimplementedWorkflowServer
// for forward compatibility.
type WorkflowServer interface {
	ImportFiles(context.Context, *ImportWorkflowRequest) (*TaskResponse, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	GetTaskPhaseProgress(context.Context, *SimpleWorkflowRequest) (*TaskPhaseProgressResponse, error)
	CreateArchive(context.Context, *ArchiveWorkflowRequest) (*TaskResponse, error)
	ExtractArchive(context.Context, *ArchiveWorkflowRequest) (*TaskResponse, error)
	CreateRemoteDownload(context.Context, *DownloadWorkflowRequest) (*ListTasksResponse, error)
	SetDownloadTaskTarget(context.Context, *SetDownloadFilesRequest) (*emptypb.Empty, error)
	CancelDownloadTask(context.Context, *SimpleWorkflowRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedWorkflowServer()
}

// UnimplementedWorkflowServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkflowServer struct{}

func (UnimplementedWorkflowServer) ImportFiles(context.Context, *ImportWorkflowRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportFiles not implemented")
}
func (UnimplementedWorkflowServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedWorkflowServer) GetTaskPhaseProgress(context.Context, *SimpleWorkflowRequest) (*TaskPhaseProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskPhaseProgress not implemented")
}
func (UnimplementedWorkflowServer) CreateArchive(context.Context, *ArchiveWorkflowRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateArchive not implemented")
}
func (UnimplementedWorkflowServer) ExtractArchive(context.Context, *ArchiveWorkflowRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtractArchive not implemented")
}
func (UnimplementedWorkflowServer) CreateRemoteDownload(context.Context, *DownloadWorkflowRequest) (*ListTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRemoteDownload not implemented")
}
func (UnimplementedWorkflowServer) SetDownloadTaskTarget(context.Context, *SetDownloadFilesRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDownloadTaskTarget not implemented")
}
func (UnimplementedWorkflowServer) CancelDownloadTask(context.Context, *SimpleWorkflowRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelDownloadTask not implemented")
}
func (UnimplementedWorkflowServer) mustEmbedUnimplementedWorkflowServer() {}
func (UnimplementedWorkflowServer) testEmbeddedByValue()                  {}

// UnsafeWorkflowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowServer will
// result in compilation errors.
type UnsafeWorkflowServer interface {
	mustEmbedUnimplementedWorkflowServer()
}

func RegisterWorkflowServer(s grpc.ServiceRegistrar, srv WorkflowServer) {
	// If the following call pancis, it indicates UnimplementedWorkflowServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Workflow_ServiceDesc, srv)
}

func _Workflow_ImportFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServer).ImportFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflow_ImportFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServer).ImportFiles(ctx, req.(*ImportWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflow_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflow_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflow_GetTaskPhaseProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServer).GetTaskPhaseProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflow_GetTaskPhaseProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServer).GetTaskPhaseProgress(ctx, req.(*SimpleWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflow_CreateArchive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServer).CreateArchive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflow_CreateArchive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServer).CreateArchive(ctx, req.(*ArchiveWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflow_ExtractArchive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServer).ExtractArchive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflow_ExtractArchive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServer).ExtractArchive(ctx, req.(*ArchiveWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflow_CreateRemoteDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServer).CreateRemoteDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflow_CreateRemoteDownload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServer).CreateRemoteDownload(ctx, req.(*DownloadWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflow_SetDownloadTaskTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDownloadFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServer).SetDownloadTaskTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflow_SetDownloadTaskTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServer).SetDownloadTaskTarget(ctx, req.(*SetDownloadFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflow_CancelDownloadTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServer).CancelDownloadTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflow_CancelDownloadTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServer).CancelDownloadTask(ctx, req.(*SimpleWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Workflow_ServiceDesc is the grpc.ServiceDesc for Workflow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Workflow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "file.workflow.v1.Workflow",
	HandlerType: (*WorkflowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ImportFiles",
			Handler:    _Workflow_ImportFiles_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _Workflow_ListTasks_Handler,
		},
		{
			MethodName: "GetTaskPhaseProgress",
			Handler:    _Workflow_GetTaskPhaseProgress_Handler,
		},
		{
			MethodName: "CreateArchive",
			Handler:    _Workflow_CreateArchive_Handler,
		},
		{
			MethodName: "ExtractArchive",
			Handler:    _Workflow_ExtractArchive_Handler,
		},
		{
			MethodName: "CreateRemoteDownload",
			Handler:    _Workflow_CreateRemoteDownload_Handler,
		},
		{
			MethodName: "SetDownloadTaskTarget",
			Handler:    _Workflow_SetDownloadTaskTarget_Handler,
		},
		{
			MethodName: "CancelDownloadTask",
			Handler:    _Workflow_CancelDownloadTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "file/workflow/v1/workflow.proto",
}
