// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUnspecified(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UNSPECIFIED.String() && e.Code == 400
}

func ErrorUnspecified(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_UNSPECIFIED.String(), fmt.Sprintf(format, args...))
}

func IsGroupNotAllowed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GROUP_NOT_ALLOWED.String() && e.Code == 400
}

func ErrorGroupNotAllowed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_GROUP_NOT_ALLOWED.String(), fmt.Sprintf(format, args...))
}

func IsGroupAdminRequired(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GROUP_ADMIN_REQUIRED.String() && e.Code == 400
}

func ErrorGroupAdminRequired(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_GROUP_ADMIN_REQUIRED.String(), fmt.Sprintf(format, args...))
}

func IsGroupNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GROUP_NOT_FOUND.String() && e.Code == 400
}

func ErrorGroupNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_GROUP_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsInvalidActionOnSystemGroup(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_ACTION_ON_SYSTEM_GROUP.String() && e.Code == 400
}

func ErrorInvalidActionOnSystemGroup(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_ACTION_ON_SYSTEM_GROUP.String(), fmt.Sprintf(format, args...))
}

func IsGroupUsedByUser(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GROUP_USED_BY_USER.String() && e.Code == 400
}

func ErrorGroupUsedByUser(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_GROUP_USED_BY_USER.String(), fmt.Sprintf(format, args...))
}

func IsChangeGroupForDefaultUser(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CHANGE_GROUP_FOR_DEFAULT_USER.String() && e.Code == 400
}

func ErrorChangeGroupForDefaultUser(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_CHANGE_GROUP_FOR_DEFAULT_USER.String(), fmt.Sprintf(format, args...))
}

func IsGroupConflict(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GROUP_CONFLICT.String() && e.Code == 400
}

func ErrorGroupConflict(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_GROUP_CONFLICT.String(), fmt.Sprintf(format, args...))
}

func IsGroupInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GROUP_INVALID.String() && e.Code == 400
}

func ErrorGroupInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_GROUP_INVALID.String(), fmt.Sprintf(format, args...))
}

func IsFulfillAdminGroup(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_FULFILL_ADMIN_GROUP.String() && e.Code == 400
}

func ErrorFulfillAdminGroup(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_FULFILL_ADMIN_GROUP.String(), fmt.Sprintf(format, args...))
}

func IsUpdateSetting(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UPDATE_SETTING.String() && e.Code == 400
}

func ErrorUpdateSetting(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_UPDATE_SETTING.String(), fmt.Sprintf(format, args...))
}
