// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v5.29.3
// source: ai/workflow/v1/workflow.proto

package v1

import (
	v1 "api/api/common/v1"
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationWorkflowCancelTasks = "/ai.workflow.v1.Workflow/CancelTasks"
const OperationWorkflowGetTask = "/ai.workflow.v1.Workflow/GetTask"
const OperationWorkflowGetTaskPhaseProgress = "/ai.workflow.v1.Workflow/GetTaskPhaseProgress"
const OperationWorkflowListTasks = "/ai.workflow.v1.Workflow/ListTasks"
const OperationWorkflowResumeTasks = "/ai.workflow.v1.Workflow/ResumeTasks"

type WorkflowHTTPServer interface {
	CancelTasks(context.Context, *CancelTaskRequest) (*emptypb.Empty, error)
	GetTask(context.Context, *SimpleRequest) (*v1.TaskResponse, error)
	GetTaskPhaseProgress(context.Context, *SimpleRequest) (*v1.TaskPhaseProgressResponse, error)
	ListTasks(context.Context, *v1.ListTasksRequest) (*v1.ListTasksResponse, error)
	ResumeTasks(context.Context, *ResumeTaskRequest) (*emptypb.Empty, error)
}

func RegisterWorkflowHTTPServer(s *http.Server, srv WorkflowHTTPServer) {
	r := s.Route("/")
	r.GET("/ai/workflow/list", _Workflow_ListTasks1_HTTP_Handler(srv))
	r.GET("/ai/workflow/{id}", _Workflow_GetTask1_HTTP_Handler(srv))
	r.GET("/ai/workflow/{id}/progress", _Workflow_GetTaskPhaseProgress0_HTTP_Handler(srv))
	r.POST("/ai/workflow/cancel", _Workflow_CancelTasks0_HTTP_Handler(srv))
	r.POST("/ai/workflow/resume", _Workflow_ResumeTasks0_HTTP_Handler(srv))
}

func _Workflow_ListTasks1_HTTP_Handler(srv WorkflowHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.ListTasksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowListTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTasks(ctx, req.(*v1.ListTasksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.ListTasksResponse)
		return ctx.Result(200, reply)
	}
}

func _Workflow_GetTask1_HTTP_Handler(srv WorkflowHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SimpleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowGetTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTask(ctx, req.(*SimpleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.TaskResponse)
		return ctx.Result(200, reply)
	}
}

func _Workflow_GetTaskPhaseProgress0_HTTP_Handler(srv WorkflowHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SimpleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowGetTaskPhaseProgress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTaskPhaseProgress(ctx, req.(*SimpleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.TaskPhaseProgressResponse)
		return ctx.Result(200, reply)
	}
}

func _Workflow_CancelTasks0_HTTP_Handler(srv WorkflowHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelTaskRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowCancelTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelTasks(ctx, req.(*CancelTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Workflow_ResumeTasks0_HTTP_Handler(srv WorkflowHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResumeTaskRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowResumeTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResumeTasks(ctx, req.(*ResumeTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type WorkflowHTTPClient interface {
	CancelTasks(ctx context.Context, req *CancelTaskRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetTask(ctx context.Context, req *SimpleRequest, opts ...http.CallOption) (rsp *v1.TaskResponse, err error)
	GetTaskPhaseProgress(ctx context.Context, req *SimpleRequest, opts ...http.CallOption) (rsp *v1.TaskPhaseProgressResponse, err error)
	ListTasks(ctx context.Context, req *v1.ListTasksRequest, opts ...http.CallOption) (rsp *v1.ListTasksResponse, err error)
	ResumeTasks(ctx context.Context, req *ResumeTaskRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type WorkflowHTTPClientImpl struct {
	cc *http.Client
}

func NewWorkflowHTTPClient(client *http.Client) WorkflowHTTPClient {
	return &WorkflowHTTPClientImpl{client}
}

func (c *WorkflowHTTPClientImpl) CancelTasks(ctx context.Context, in *CancelTaskRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/ai/workflow/cancel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWorkflowCancelTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WorkflowHTTPClientImpl) GetTask(ctx context.Context, in *SimpleRequest, opts ...http.CallOption) (*v1.TaskResponse, error) {
	var out v1.TaskResponse
	pattern := "/ai/workflow/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWorkflowGetTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WorkflowHTTPClientImpl) GetTaskPhaseProgress(ctx context.Context, in *SimpleRequest, opts ...http.CallOption) (*v1.TaskPhaseProgressResponse, error) {
	var out v1.TaskPhaseProgressResponse
	pattern := "/ai/workflow/{id}/progress"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWorkflowGetTaskPhaseProgress))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WorkflowHTTPClientImpl) ListTasks(ctx context.Context, in *v1.ListTasksRequest, opts ...http.CallOption) (*v1.ListTasksResponse, error) {
	var out v1.ListTasksResponse
	pattern := "/ai/workflow/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWorkflowListTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WorkflowHTTPClientImpl) ResumeTasks(ctx context.Context, in *ResumeTaskRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/ai/workflow/resume"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWorkflowResumeTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
