// Code generated by entproto. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: user/common/v1/entpb.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User_Status int32

const (
	User_STATUS_ACTIVE        User_Status = 0
	User_STATUS_INACTIVE      User_Status = 1
	User_STATUS_MANUAL_BANNED User_Status = 2
	User_STATUS_SYS_BANNED    User_Status = 3
)

// Enum value maps for User_Status.
var (
	User_Status_name = map[int32]string{
		0: "STATUS_ACTIVE",
		1: "STATUS_INACTIVE",
		2: "STATUS_MANUAL_BANNED",
		3: "STATUS_SYS_BANNED",
	}
	User_Status_value = map[string]int32{
		"STATUS_ACTIVE":        0,
		"STATUS_INACTIVE":      1,
		"STATUS_MANUAL_BANNED": 2,
		"STATUS_SYS_BANNED":    3,
	}
)

func (x User_Status) Enum() *User_Status {
	p := new(User_Status)
	*p = x
	return p
}

func (x User_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (User_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_user_common_v1_entpb_proto_enumTypes[0].Descriptor()
}

func (User_Status) Type() protoreflect.EnumType {
	return &file_user_common_v1_entpb_proto_enumTypes[0]
}

func (x User_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use User_Status.Descriptor instead.
func (User_Status) EnumDescriptor() ([]byte, []int) {
	return file_user_common_v1_entpb_proto_rawDescGZIP(), []int{3, 0}
}

type Group struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt         *timestamppb.Timestamp `protobuf:"bytes,102,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MaxStorage        *wrapperspb.Int64Value `protobuf:"bytes,3,opt,name=max_storage,json=maxStorage,proto3" json:"max_storage,omitempty"`
	SpeedLimit        *wrapperspb.Int64Value `protobuf:"bytes,4,opt,name=speed_limit,json=speedLimit,proto3" json:"speed_limit,omitempty"`
	Permissions       []byte                 `protobuf:"bytes,5,opt,name=permissions,proto3" json:"permissions,omitempty"`
	Settings          *GroupSetting          `protobuf:"bytes,6,opt,name=settings,proto3" json:"settings,omitempty"`
	StoragePolicyId   *wrapperspb.Int64Value `protobuf:"bytes,7,opt,name=storage_policy_id,json=storagePolicyId,proto3" json:"storage_policy_id,omitempty"`
	StoragePolicyInfo *StoragePolicyInfo     `protobuf:"bytes,8,opt,name=storage_policy_info,json=storagePolicyInfo,proto3" json:"storage_policy_info,omitempty"`
	Users             []*User                `protobuf:"bytes,80,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_user_common_v1_entpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_user_common_v1_entpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_user_common_v1_entpb_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Group) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Group) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Group) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetMaxStorage() *wrapperspb.Int64Value {
	if x != nil {
		return x.MaxStorage
	}
	return nil
}

func (x *Group) GetSpeedLimit() *wrapperspb.Int64Value {
	if x != nil {
		return x.SpeedLimit
	}
	return nil
}

func (x *Group) GetPermissions() []byte {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Group) GetSettings() *GroupSetting {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Group) GetStoragePolicyId() *wrapperspb.Int64Value {
	if x != nil {
		return x.StoragePolicyId
	}
	return nil
}

func (x *Group) GetStoragePolicyInfo() *StoragePolicyInfo {
	if x != nil {
		return x.StoragePolicyInfo
	}
	return nil
}

func (x *Group) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type Passkey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,102,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CredentialId  string                 `protobuf:"bytes,3,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Credential    string                 `protobuf:"bytes,5,opt,name=credential,proto3" json:"credential,omitempty"`
	UsedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=used_at,json=usedAt,proto3" json:"used_at,omitempty"`
	Users         *User                  `protobuf:"bytes,80,opt,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Passkey) Reset() {
	*x = Passkey{}
	mi := &file_user_common_v1_entpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Passkey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Passkey) ProtoMessage() {}

func (x *Passkey) ProtoReflect() protoreflect.Message {
	mi := &file_user_common_v1_entpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Passkey.ProtoReflect.Descriptor instead.
func (*Passkey) Descriptor() ([]byte, []int) {
	return file_user_common_v1_entpb_proto_rawDescGZIP(), []int{1}
}

func (x *Passkey) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Passkey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Passkey) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Passkey) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Passkey) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Passkey) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *Passkey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Passkey) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *Passkey) GetUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UsedAt
	}
	return nil
}

func (x *Passkey) GetUsers() *User {
	if x != nil {
		return x.Users
	}
	return nil
}

type Setting struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp  `protobuf:"bytes,102,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Setting) Reset() {
	*x = Setting{}
	mi := &file_user_common_v1_entpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Setting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setting) ProtoMessage() {}

func (x *Setting) ProtoReflect() protoreflect.Message {
	mi := &file_user_common_v1_entpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setting.ProtoReflect.Descriptor instead.
func (*Setting) Descriptor() ([]byte, []int) {
	return file_user_common_v1_entpb_proto_rawDescGZIP(), []int{2}
}

func (x *Setting) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Setting) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Setting) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Setting) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Setting) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Setting) GetValue() *wrapperspb.StringValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type User struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Id              int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt       *timestamppb.Timestamp  `protobuf:"bytes,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp  `protobuf:"bytes,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt       *timestamppb.Timestamp  `protobuf:"bytes,102,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Email           string                  `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Nick            string                  `protobuf:"bytes,3,opt,name=nick,proto3" json:"nick,omitempty"`
	Password        *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Status          User_Status             `protobuf:"varint,5,opt,name=status,proto3,enum=user.common.v1.User_Status" json:"status,omitempty"`
	Storage         int64                   `protobuf:"varint,6,opt,name=storage,proto3" json:"storage,omitempty"`
	TwoFactorSecret *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=two_factor_secret,json=twoFactorSecret,proto3" json:"two_factor_secret,omitempty"`
	Avatar          *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Settings        *UserSetting            `protobuf:"bytes,9,opt,name=settings,proto3" json:"settings,omitempty"`
	GroupUsers      int64                   `protobuf:"varint,10,opt,name=group_users,json=groupUsers,proto3" json:"group_users,omitempty"`
	Group           *Group                  `protobuf:"bytes,80,opt,name=group,proto3" json:"group,omitempty"`
	Passkey         []*Passkey              `protobuf:"bytes,81,rep,name=passkey,proto3" json:"passkey,omitempty"`
	DavAccounts     []*DavAccount           `protobuf:"bytes,82,rep,name=dav_accounts,json=davAccounts,proto3" json:"dav_accounts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_common_v1_entpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_common_v1_entpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_common_v1_entpb_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *User) GetPassword() *wrapperspb.StringValue {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *User) GetStatus() User_Status {
	if x != nil {
		return x.Status
	}
	return User_STATUS_ACTIVE
}

func (x *User) GetStorage() int64 {
	if x != nil {
		return x.Storage
	}
	return 0
}

func (x *User) GetTwoFactorSecret() *wrapperspb.StringValue {
	if x != nil {
		return x.TwoFactorSecret
	}
	return nil
}

func (x *User) GetAvatar() *wrapperspb.StringValue {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *User) GetSettings() *UserSetting {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *User) GetGroupUsers() int64 {
	if x != nil {
		return x.GroupUsers
	}
	return 0
}

func (x *User) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *User) GetPasskey() []*Passkey {
	if x != nil {
		return x.Passkey
	}
	return nil
}

func (x *User) GetDavAccounts() []*DavAccount {
	if x != nil {
		return x.DavAccounts
	}
	return nil
}

type DavAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,102,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uri           string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Options       []byte                 `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	Props         *DavAccountProps       `protobuf:"bytes,6,opt,name=props,proto3" json:"props,omitempty"`
	OwnerId       int64                  `protobuf:"varint,7,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DavAccount) Reset() {
	*x = DavAccount{}
	mi := &file_user_common_v1_entpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DavAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DavAccount) ProtoMessage() {}

func (x *DavAccount) ProtoReflect() protoreflect.Message {
	mi := &file_user_common_v1_entpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DavAccount.ProtoReflect.Descriptor instead.
func (*DavAccount) Descriptor() ([]byte, []int) {
	return file_user_common_v1_entpb_proto_rawDescGZIP(), []int{4}
}

func (x *DavAccount) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DavAccount) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DavAccount) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DavAccount) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *DavAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DavAccount) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *DavAccount) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DavAccount) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *DavAccount) GetProps() *DavAccountProps {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *DavAccount) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

var File_user_common_v1_entpb_proto protoreflect.FileDescriptor

const file_user_common_v1_entpb_proto_rawDesc = "" +
	"\n" +
	"\x1auser/common/v1/entpb.proto\x12\x0euser.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1buser/common/v1/common.proto\"\xfc\x04\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x129\n" +
	"\n" +
	"created_at\x18d \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18f \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12<\n" +
	"\vmax_storage\x18\x03 \x01(\v2\x1b.google.protobuf.Int64ValueR\n" +
	"maxStorage\x12<\n" +
	"\vspeed_limit\x18\x04 \x01(\v2\x1b.google.protobuf.Int64ValueR\n" +
	"speedLimit\x12 \n" +
	"\vpermissions\x18\x05 \x01(\fR\vpermissions\x128\n" +
	"\bsettings\x18\x06 \x01(\v2\x1c.user.common.v1.GroupSettingR\bsettings\x12G\n" +
	"\x11storage_policy_id\x18\a \x01(\v2\x1b.google.protobuf.Int64ValueR\x0fstoragePolicyId\x12Q\n" +
	"\x13storage_policy_info\x18\b \x01(\v2!.user.common.v1.StoragePolicyInfoR\x11storagePolicyInfo\x12*\n" +
	"\x05users\x18P \x03(\v2\x14.user.common.v1.UserR\x05users\"\x9d\x03\n" +
	"\aPasskey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x129\n" +
	"\n" +
	"created_at\x18d \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18f \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12#\n" +
	"\rcredential_id\x18\x03 \x01(\tR\fcredentialId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"credential\x18\x05 \x01(\tR\n" +
	"credential\x123\n" +
	"\aused_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06usedAt\x12*\n" +
	"\x05users\x18P \x01(\v2\x14.user.common.v1.UserR\x05users\"\x92\x02\n" +
	"\aSetting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x129\n" +
	"\n" +
	"created_at\x18d \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18f \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x122\n" +
	"\x05value\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x05value\"\xd6\x06\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x129\n" +
	"\n" +
	"created_at\x18d \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18f \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04nick\x18\x03 \x01(\tR\x04nick\x128\n" +
	"\bpassword\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\bpassword\x123\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1b.user.common.v1.User.StatusR\x06status\x12\x18\n" +
	"\astorage\x18\x06 \x01(\x03R\astorage\x12H\n" +
	"\x11two_factor_secret\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\x0ftwoFactorSecret\x124\n" +
	"\x06avatar\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\x06avatar\x127\n" +
	"\bsettings\x18\t \x01(\v2\x1b.user.common.v1.UserSettingR\bsettings\x12\x1f\n" +
	"\vgroup_users\x18\n" +
	" \x01(\x03R\n" +
	"groupUsers\x12+\n" +
	"\x05group\x18P \x01(\v2\x15.user.common.v1.GroupR\x05group\x121\n" +
	"\apasskey\x18Q \x03(\v2\x17.user.common.v1.PasskeyR\apasskey\x12=\n" +
	"\fdav_accounts\x18R \x03(\v2\x1a.user.common.v1.DavAccountR\vdavAccounts\"a\n" +
	"\x06Status\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x00\x12\x13\n" +
	"\x0fSTATUS_INACTIVE\x10\x01\x12\x18\n" +
	"\x14STATUS_MANUAL_BANNED\x10\x02\x12\x15\n" +
	"\x11STATUS_SYS_BANNED\x10\x03\"\xfb\x02\n" +
	"\n" +
	"DavAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x129\n" +
	"\n" +
	"created_at\x18d \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18f \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x18\n" +
	"\aoptions\x18\x05 \x01(\fR\aoptions\x125\n" +
	"\x05props\x18\x06 \x01(\v2\x1f.user.common.v1.DavAccountPropsR\x05props\x12\x19\n" +
	"\bowner_id\x18\a \x01(\x03R\aownerIdB\x1bZ\x19api/api/user/common/v1;v1b\x06proto3"

var (
	file_user_common_v1_entpb_proto_rawDescOnce sync.Once
	file_user_common_v1_entpb_proto_rawDescData []byte
)

func file_user_common_v1_entpb_proto_rawDescGZIP() []byte {
	file_user_common_v1_entpb_proto_rawDescOnce.Do(func() {
		file_user_common_v1_entpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_common_v1_entpb_proto_rawDesc), len(file_user_common_v1_entpb_proto_rawDesc)))
	})
	return file_user_common_v1_entpb_proto_rawDescData
}

var file_user_common_v1_entpb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_common_v1_entpb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_common_v1_entpb_proto_goTypes = []any{
	(User_Status)(0),               // 0: user.common.v1.User.Status
	(*Group)(nil),                  // 1: user.common.v1.Group
	(*Passkey)(nil),                // 2: user.common.v1.Passkey
	(*Setting)(nil),                // 3: user.common.v1.Setting
	(*User)(nil),                   // 4: user.common.v1.User
	(*DavAccount)(nil),             // 5: user.common.v1.DavAccount
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
	(*wrapperspb.Int64Value)(nil),  // 7: google.protobuf.Int64Value
	(*GroupSetting)(nil),           // 8: user.common.v1.GroupSetting
	(*StoragePolicyInfo)(nil),      // 9: user.common.v1.StoragePolicyInfo
	(*wrapperspb.StringValue)(nil), // 10: google.protobuf.StringValue
	(*UserSetting)(nil),            // 11: user.common.v1.UserSetting
	(*DavAccountProps)(nil),        // 12: user.common.v1.DavAccountProps
}
var file_user_common_v1_entpb_proto_depIdxs = []int32{
	6,  // 0: user.common.v1.Group.created_at:type_name -> google.protobuf.Timestamp
	6,  // 1: user.common.v1.Group.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 2: user.common.v1.Group.deleted_at:type_name -> google.protobuf.Timestamp
	7,  // 3: user.common.v1.Group.max_storage:type_name -> google.protobuf.Int64Value
	7,  // 4: user.common.v1.Group.speed_limit:type_name -> google.protobuf.Int64Value
	8,  // 5: user.common.v1.Group.settings:type_name -> user.common.v1.GroupSetting
	7,  // 6: user.common.v1.Group.storage_policy_id:type_name -> google.protobuf.Int64Value
	9,  // 7: user.common.v1.Group.storage_policy_info:type_name -> user.common.v1.StoragePolicyInfo
	4,  // 8: user.common.v1.Group.users:type_name -> user.common.v1.User
	6,  // 9: user.common.v1.Passkey.created_at:type_name -> google.protobuf.Timestamp
	6,  // 10: user.common.v1.Passkey.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 11: user.common.v1.Passkey.deleted_at:type_name -> google.protobuf.Timestamp
	6,  // 12: user.common.v1.Passkey.used_at:type_name -> google.protobuf.Timestamp
	4,  // 13: user.common.v1.Passkey.users:type_name -> user.common.v1.User
	6,  // 14: user.common.v1.Setting.created_at:type_name -> google.protobuf.Timestamp
	6,  // 15: user.common.v1.Setting.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 16: user.common.v1.Setting.deleted_at:type_name -> google.protobuf.Timestamp
	10, // 17: user.common.v1.Setting.value:type_name -> google.protobuf.StringValue
	6,  // 18: user.common.v1.User.created_at:type_name -> google.protobuf.Timestamp
	6,  // 19: user.common.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 20: user.common.v1.User.deleted_at:type_name -> google.protobuf.Timestamp
	10, // 21: user.common.v1.User.password:type_name -> google.protobuf.StringValue
	0,  // 22: user.common.v1.User.status:type_name -> user.common.v1.User.Status
	10, // 23: user.common.v1.User.two_factor_secret:type_name -> google.protobuf.StringValue
	10, // 24: user.common.v1.User.avatar:type_name -> google.protobuf.StringValue
	11, // 25: user.common.v1.User.settings:type_name -> user.common.v1.UserSetting
	1,  // 26: user.common.v1.User.group:type_name -> user.common.v1.Group
	2,  // 27: user.common.v1.User.passkey:type_name -> user.common.v1.Passkey
	5,  // 28: user.common.v1.User.dav_accounts:type_name -> user.common.v1.DavAccount
	6,  // 29: user.common.v1.DavAccount.created_at:type_name -> google.protobuf.Timestamp
	6,  // 30: user.common.v1.DavAccount.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 31: user.common.v1.DavAccount.deleted_at:type_name -> google.protobuf.Timestamp
	12, // 32: user.common.v1.DavAccount.props:type_name -> user.common.v1.DavAccountProps
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_user_common_v1_entpb_proto_init() }
func file_user_common_v1_entpb_proto_init() {
	if File_user_common_v1_entpb_proto != nil {
		return
	}
	file_user_common_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_common_v1_entpb_proto_rawDesc), len(file_user_common_v1_entpb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_common_v1_entpb_proto_goTypes,
		DependencyIndexes: file_user_common_v1_entpb_proto_depIdxs,
		EnumInfos:         file_user_common_v1_entpb_proto_enumTypes,
		MessageInfos:      file_user_common_v1_entpb_proto_msgTypes,
	}.Build()
	File_user_common_v1_entpb_proto = out.File
	file_user_common_v1_entpb_proto_goTypes = nil
	file_user_common_v1_entpb_proto_depIdxs = nil
}
