version: '3'
services:
  gateway:
    build: .
    network_mode: host
    restart: always
    volumes:
      - ./cmd/gateway/common.yaml:/data/conf/common.yaml
    deploy:
      resources:
        limits:
          cpus: '8.00'
          memory: '8192M'
