// Code generated by ent, DO NOT EDIT.

package aimodel

import (
	"ai/ent/predicate"
	"entmodule"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AiModel {
	return predicate.AiModel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AiModel {
	return predicate.AiModel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AiModel {
	return predicate.AiModel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AiModel {
	return predicate.AiModel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AiModel {
	return predicate.AiModel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AiModel {
	return predicate.AiModel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AiModel {
	return predicate.AiModel(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldName, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldType, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldPlatform, v))
}

// Sort applies equality check predicate on the "sort" field. It's identical to SortEQ.
func Sort(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldSort, v))
}

// Temperature applies equality check predicate on the "temperature" field. It's identical to TemperatureEQ.
func Temperature(v float64) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldTemperature, v))
}

// MaxTokens applies equality check predicate on the "max_tokens" field. It's identical to MaxTokensEQ.
func MaxTokens(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldMaxTokens, v))
}

// MaxContext applies equality check predicate on the "max_context" field. It's identical to MaxContextEQ.
func MaxContext(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldMaxContext, v))
}

// KeyID applies equality check predicate on the "key_id" field. It's identical to KeyIDEQ.
func KeyID(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldKeyID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.AiModel {
	return predicate.AiModel(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.AiModel {
	return predicate.AiModel(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.AiModel {
	return predicate.AiModel(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AiModel {
	return predicate.AiModel(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AiModel {
	return predicate.AiModel(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.AiModel {
	return predicate.AiModel(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.AiModel {
	return predicate.AiModel(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldContainsFold(FieldType, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.AiModel {
	return predicate.AiModel(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.AiModel {
	return predicate.AiModel(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.AiModel {
	return predicate.AiModel(sql.FieldContainsFold(FieldPlatform, v))
}

// SortEQ applies the EQ predicate on the "sort" field.
func SortEQ(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldSort, v))
}

// SortNEQ applies the NEQ predicate on the "sort" field.
func SortNEQ(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldNEQ(FieldSort, v))
}

// SortIn applies the In predicate on the "sort" field.
func SortIn(vs ...int) predicate.AiModel {
	return predicate.AiModel(sql.FieldIn(FieldSort, vs...))
}

// SortNotIn applies the NotIn predicate on the "sort" field.
func SortNotIn(vs ...int) predicate.AiModel {
	return predicate.AiModel(sql.FieldNotIn(FieldSort, vs...))
}

// SortGT applies the GT predicate on the "sort" field.
func SortGT(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldGT(FieldSort, v))
}

// SortGTE applies the GTE predicate on the "sort" field.
func SortGTE(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldGTE(FieldSort, v))
}

// SortLT applies the LT predicate on the "sort" field.
func SortLT(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldLT(FieldSort, v))
}

// SortLTE applies the LTE predicate on the "sort" field.
func SortLTE(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldLTE(FieldSort, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v entmodule.Status) predicate.AiModel {
	vc := v
	return predicate.AiModel(sql.FieldEQ(FieldStatus, vc))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v entmodule.Status) predicate.AiModel {
	vc := v
	return predicate.AiModel(sql.FieldNEQ(FieldStatus, vc))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...entmodule.Status) predicate.AiModel {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AiModel(sql.FieldIn(FieldStatus, v...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...entmodule.Status) predicate.AiModel {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.AiModel(sql.FieldNotIn(FieldStatus, v...))
}

// TemperatureEQ applies the EQ predicate on the "temperature" field.
func TemperatureEQ(v float64) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldTemperature, v))
}

// TemperatureNEQ applies the NEQ predicate on the "temperature" field.
func TemperatureNEQ(v float64) predicate.AiModel {
	return predicate.AiModel(sql.FieldNEQ(FieldTemperature, v))
}

// TemperatureIn applies the In predicate on the "temperature" field.
func TemperatureIn(vs ...float64) predicate.AiModel {
	return predicate.AiModel(sql.FieldIn(FieldTemperature, vs...))
}

// TemperatureNotIn applies the NotIn predicate on the "temperature" field.
func TemperatureNotIn(vs ...float64) predicate.AiModel {
	return predicate.AiModel(sql.FieldNotIn(FieldTemperature, vs...))
}

// TemperatureGT applies the GT predicate on the "temperature" field.
func TemperatureGT(v float64) predicate.AiModel {
	return predicate.AiModel(sql.FieldGT(FieldTemperature, v))
}

// TemperatureGTE applies the GTE predicate on the "temperature" field.
func TemperatureGTE(v float64) predicate.AiModel {
	return predicate.AiModel(sql.FieldGTE(FieldTemperature, v))
}

// TemperatureLT applies the LT predicate on the "temperature" field.
func TemperatureLT(v float64) predicate.AiModel {
	return predicate.AiModel(sql.FieldLT(FieldTemperature, v))
}

// TemperatureLTE applies the LTE predicate on the "temperature" field.
func TemperatureLTE(v float64) predicate.AiModel {
	return predicate.AiModel(sql.FieldLTE(FieldTemperature, v))
}

// MaxTokensEQ applies the EQ predicate on the "max_tokens" field.
func MaxTokensEQ(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldMaxTokens, v))
}

// MaxTokensNEQ applies the NEQ predicate on the "max_tokens" field.
func MaxTokensNEQ(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldNEQ(FieldMaxTokens, v))
}

// MaxTokensIn applies the In predicate on the "max_tokens" field.
func MaxTokensIn(vs ...int) predicate.AiModel {
	return predicate.AiModel(sql.FieldIn(FieldMaxTokens, vs...))
}

// MaxTokensNotIn applies the NotIn predicate on the "max_tokens" field.
func MaxTokensNotIn(vs ...int) predicate.AiModel {
	return predicate.AiModel(sql.FieldNotIn(FieldMaxTokens, vs...))
}

// MaxTokensGT applies the GT predicate on the "max_tokens" field.
func MaxTokensGT(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldGT(FieldMaxTokens, v))
}

// MaxTokensGTE applies the GTE predicate on the "max_tokens" field.
func MaxTokensGTE(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldGTE(FieldMaxTokens, v))
}

// MaxTokensLT applies the LT predicate on the "max_tokens" field.
func MaxTokensLT(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldLT(FieldMaxTokens, v))
}

// MaxTokensLTE applies the LTE predicate on the "max_tokens" field.
func MaxTokensLTE(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldLTE(FieldMaxTokens, v))
}

// MaxContextEQ applies the EQ predicate on the "max_context" field.
func MaxContextEQ(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldMaxContext, v))
}

// MaxContextNEQ applies the NEQ predicate on the "max_context" field.
func MaxContextNEQ(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldNEQ(FieldMaxContext, v))
}

// MaxContextIn applies the In predicate on the "max_context" field.
func MaxContextIn(vs ...int) predicate.AiModel {
	return predicate.AiModel(sql.FieldIn(FieldMaxContext, vs...))
}

// MaxContextNotIn applies the NotIn predicate on the "max_context" field.
func MaxContextNotIn(vs ...int) predicate.AiModel {
	return predicate.AiModel(sql.FieldNotIn(FieldMaxContext, vs...))
}

// MaxContextGT applies the GT predicate on the "max_context" field.
func MaxContextGT(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldGT(FieldMaxContext, v))
}

// MaxContextGTE applies the GTE predicate on the "max_context" field.
func MaxContextGTE(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldGTE(FieldMaxContext, v))
}

// MaxContextLT applies the LT predicate on the "max_context" field.
func MaxContextLT(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldLT(FieldMaxContext, v))
}

// MaxContextLTE applies the LTE predicate on the "max_context" field.
func MaxContextLTE(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldLTE(FieldMaxContext, v))
}

// KeyIDEQ applies the EQ predicate on the "key_id" field.
func KeyIDEQ(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldEQ(FieldKeyID, v))
}

// KeyIDNEQ applies the NEQ predicate on the "key_id" field.
func KeyIDNEQ(v int) predicate.AiModel {
	return predicate.AiModel(sql.FieldNEQ(FieldKeyID, v))
}

// KeyIDIn applies the In predicate on the "key_id" field.
func KeyIDIn(vs ...int) predicate.AiModel {
	return predicate.AiModel(sql.FieldIn(FieldKeyID, vs...))
}

// KeyIDNotIn applies the NotIn predicate on the "key_id" field.
func KeyIDNotIn(vs ...int) predicate.AiModel {
	return predicate.AiModel(sql.FieldNotIn(FieldKeyID, vs...))
}

// HasAiAPIKey applies the HasEdge predicate on the "ai_api_key" edge.
func HasAiAPIKey() predicate.AiModel {
	return predicate.AiModel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AiAPIKeyTable, AiAPIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAiAPIKeyWith applies the HasEdge predicate on the "ai_api_key" edge with a given conditions (other predicates).
func HasAiAPIKeyWith(preds ...predicate.AiApiKey) predicate.AiModel {
	return predicate.AiModel(func(s *sql.Selector) {
		step := newAiAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AiModel) predicate.AiModel {
	return predicate.AiModel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AiModel) predicate.AiModel {
	return predicate.AiModel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AiModel) predicate.AiModel {
	return predicate.AiModel(sql.NotPredicates(p))
}
