// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: gateway/middleware/security/v1/security.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Security middleware config.
type Security struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CacheControl  *string                `protobuf:"bytes,1,opt,name=cache_control,json=cacheControl,proto3,oneof" json:"cache_control,omitempty"`
	WhiteList     []string               `protobuf:"bytes,2,rep,name=white_list,json=whiteList,proto3" json:"white_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security) Reset() {
	*x = Security{}
	mi := &file_gateway_middleware_security_v1_security_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security) ProtoMessage() {}

func (x *Security) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_middleware_security_v1_security_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security.ProtoReflect.Descriptor instead.
func (*Security) Descriptor() ([]byte, []int) {
	return file_gateway_middleware_security_v1_security_proto_rawDescGZIP(), []int{0}
}

func (x *Security) GetCacheControl() string {
	if x != nil && x.CacheControl != nil {
		return *x.CacheControl
	}
	return ""
}

func (x *Security) GetWhiteList() []string {
	if x != nil {
		return x.WhiteList
	}
	return nil
}

var File_gateway_middleware_security_v1_security_proto protoreflect.FileDescriptor

const file_gateway_middleware_security_v1_security_proto_rawDesc = "" +
	"\n" +
	"-gateway/middleware/security/v1/security.proto\x12\x1egateway.middleware.security.v1\"e\n" +
	"\bSecurity\x12(\n" +
	"\rcache_control\x18\x01 \x01(\tH\x00R\fcacheControl\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"white_list\x18\x02 \x03(\tR\twhiteListB\x10\n" +
	"\x0e_cache_controlB,Z*gateway/api/gateway/middleware/security/v1b\x06proto3"

var (
	file_gateway_middleware_security_v1_security_proto_rawDescOnce sync.Once
	file_gateway_middleware_security_v1_security_proto_rawDescData []byte
)

func file_gateway_middleware_security_v1_security_proto_rawDescGZIP() []byte {
	file_gateway_middleware_security_v1_security_proto_rawDescOnce.Do(func() {
		file_gateway_middleware_security_v1_security_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_middleware_security_v1_security_proto_rawDesc), len(file_gateway_middleware_security_v1_security_proto_rawDesc)))
	})
	return file_gateway_middleware_security_v1_security_proto_rawDescData
}

var file_gateway_middleware_security_v1_security_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gateway_middleware_security_v1_security_proto_goTypes = []any{
	(*Security)(nil), // 0: gateway.middleware.security.v1.Security
}
var file_gateway_middleware_security_v1_security_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_middleware_security_v1_security_proto_init() }
func file_gateway_middleware_security_v1_security_proto_init() {
	if File_gateway_middleware_security_v1_security_proto != nil {
		return
	}
	file_gateway_middleware_security_v1_security_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_middleware_security_v1_security_proto_rawDesc), len(file_gateway_middleware_security_v1_security_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_middleware_security_v1_security_proto_goTypes,
		DependencyIndexes: file_gateway_middleware_security_v1_security_proto_depIdxs,
		MessageInfos:      file_gateway_middleware_security_v1_security_proto_msgTypes,
	}.Build()
	File_gateway_middleware_security_v1_security_proto = out.File
	file_gateway_middleware_security_v1_security_proto_goTypes = nil
	file_gateway_middleware_security_v1_security_proto_depIdxs = nil
}
