// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v5.29.3
// source: file/share/v1/share.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationShareCreateShare = "/file.share.v1.Share/CreateShare"
const OperationShareDeleteShare = "/file.share.v1.Share/DeleteShare"
const OperationShareEditShare = "/file.share.v1.Share/EditShare"
const OperationShareGetShare = "/file.share.v1.Share/GetShare"
const OperationShareListShares = "/file.share.v1.Share/ListShares"
const OperationShareListUserPublicShare = "/file.share.v1.Share/ListUserPublicShare"

type ShareHTTPServer interface {
	CreateShare(context.Context, *UpsertShareRequest) (*UpsertShareResponse, error)
	DeleteShare(context.Context, *DeleteShareRequest) (*emptypb.Empty, error)
	EditShare(context.Context, *UpsertShareRequest) (*UpsertShareResponse, error)
	GetShare(context.Context, *GetShareRequest) (*GetShareResponse, error)
	ListShares(context.Context, *ListSharesRequest) (*ListSharesResponse, error)
	ListUserPublicShare(context.Context, *ListSharesRequest) (*ListSharesResponse, error)
}

func RegisterShareHTTPServer(s *http.Server, srv ShareHTTPServer) {
	r := s.Route("/")
	r.PUT("/share/create", _Share_CreateShare0_HTTP_Handler(srv))
	r.POST("/share/{id}", _Share_EditShare0_HTTP_Handler(srv))
	r.GET("/share/info/{id}", _Share_GetShare1_HTTP_Handler(srv))
	r.GET("/share/list", _Share_ListShares1_HTTP_Handler(srv))
	r.DELETE("/share/{id}", _Share_DeleteShare0_HTTP_Handler(srv))
	r.GET("/share/user/{id}", _Share_ListUserPublicShare0_HTTP_Handler(srv))
}

func _Share_CreateShare0_HTTP_Handler(srv ShareHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpsertShareRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShareCreateShare)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateShare(ctx, req.(*UpsertShareRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpsertShareResponse)
		return ctx.Result(200, reply)
	}
}

func _Share_EditShare0_HTTP_Handler(srv ShareHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpsertShareRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShareEditShare)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EditShare(ctx, req.(*UpsertShareRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpsertShareResponse)
		return ctx.Result(200, reply)
	}
}

func _Share_GetShare1_HTTP_Handler(srv ShareHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetShareRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShareGetShare)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetShare(ctx, req.(*GetShareRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetShareResponse)
		return ctx.Result(200, reply)
	}
}

func _Share_ListShares1_HTTP_Handler(srv ShareHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSharesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShareListShares)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListShares(ctx, req.(*ListSharesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSharesResponse)
		return ctx.Result(200, reply)
	}
}

func _Share_DeleteShare0_HTTP_Handler(srv ShareHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteShareRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShareDeleteShare)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteShare(ctx, req.(*DeleteShareRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Share_ListUserPublicShare0_HTTP_Handler(srv ShareHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSharesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShareListUserPublicShare)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListUserPublicShare(ctx, req.(*ListSharesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSharesResponse)
		return ctx.Result(200, reply)
	}
}

type ShareHTTPClient interface {
	CreateShare(ctx context.Context, req *UpsertShareRequest, opts ...http.CallOption) (rsp *UpsertShareResponse, err error)
	DeleteShare(ctx context.Context, req *DeleteShareRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	EditShare(ctx context.Context, req *UpsertShareRequest, opts ...http.CallOption) (rsp *UpsertShareResponse, err error)
	GetShare(ctx context.Context, req *GetShareRequest, opts ...http.CallOption) (rsp *GetShareResponse, err error)
	ListShares(ctx context.Context, req *ListSharesRequest, opts ...http.CallOption) (rsp *ListSharesResponse, err error)
	ListUserPublicShare(ctx context.Context, req *ListSharesRequest, opts ...http.CallOption) (rsp *ListSharesResponse, err error)
}

type ShareHTTPClientImpl struct {
	cc *http.Client
}

func NewShareHTTPClient(client *http.Client) ShareHTTPClient {
	return &ShareHTTPClientImpl{client}
}

func (c *ShareHTTPClientImpl) CreateShare(ctx context.Context, in *UpsertShareRequest, opts ...http.CallOption) (*UpsertShareResponse, error) {
	var out UpsertShareResponse
	pattern := "/share/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShareCreateShare))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShareHTTPClientImpl) DeleteShare(ctx context.Context, in *DeleteShareRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/share/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShareDeleteShare))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShareHTTPClientImpl) EditShare(ctx context.Context, in *UpsertShareRequest, opts ...http.CallOption) (*UpsertShareResponse, error) {
	var out UpsertShareResponse
	pattern := "/share/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShareEditShare))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShareHTTPClientImpl) GetShare(ctx context.Context, in *GetShareRequest, opts ...http.CallOption) (*GetShareResponse, error) {
	var out GetShareResponse
	pattern := "/share/info/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShareGetShare))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShareHTTPClientImpl) ListShares(ctx context.Context, in *ListSharesRequest, opts ...http.CallOption) (*ListSharesResponse, error) {
	var out ListSharesResponse
	pattern := "/share/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShareListShares))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShareHTTPClientImpl) ListUserPublicShare(ctx context.Context, in *ListSharesRequest, opts ...http.CallOption) (*ListSharesResponse, error) {
	var out ListSharesResponse
	pattern := "/share/user/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShareListUserPublicShare))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
